### ISSUE TITLE
Adding heating preset

### ISSUE THREAD

**Issue by moikorg** [JonahKr/power-distribution-card#100]
Hi
I am using the power-distribution-card and I like it a lot. I finally have sensors for my EV-wallbox, photovoltaic installation and also for my electric (heat pump) heating.
I'd like to display the heating in the power-distribution-card, therefore it would be nice to add a new present entry.

I'd tried to create and push a new branch for a future pull request, but I don't have the access rights to it, thus here my proposition for the
[presets.ts.gz](https://github.com/JonahKr/power-distribution-card/files/7941952/presets.ts.gz)

**Comment by JonahKr** [comment]
Hey there @moikorg , 👋 

To contribute to a public repository on Github/Gitlab, you first have to fork the project, apply the changes to your fork and then create a pull request to merge it into the origin (this repo). 
There is an excellent 100s Youtube Video you can check out for a bit more guidance: https://www.youtube.com/watch?v=8lGpZkjnkt4

Anyways: I will just take the changes from the file you uploaded and apply it in the next update.

Thanks for your efforts!

Take care and stay safe! 👍

**Comment by moikorg** [comment]
Thanks for the application of the change and thanks for the Github video hint ;-)

**Comment by JonahKr** [comment]
Hi again,
i just applied the changes and will release them in a second.

Take care and stay safe! 👍
