### ISSUE TITLE
HA 2022.3b1 destroys graphical card editor

### ISSUE THREAD

**Issue by KNXBroker** [JonahKr/power-distribution-card#103]
HA 2022.3b1 destroys graphical card editor, see screenshot below

![image](https://user-images.githubusercontent.com/25910703/155600388-fd8a25d3-85cb-41b3-9a81-ceb36abdc548.png)

**Comment by JonahKr** [comment]
Hey there 👋 @KNXBroker
Yes I am aware of the issue. I got informed by one of the devs on discord. I will try to get it done before the release 2022.3 but cannot promise anything atm.
Thanks for bringing it up though 👍
It's nice to know that my card is used by awesome beta testers aswell! 😅

Take care and stay safe!

Jonah

**Comment by JonahKr** [comment]
I will release a fix tomorrow if I can wrap my head around it😅

**Comment by louis702** [comment]
Please fix it soon. I miss it. ;)

**Comment by JonahKr** [comment]
Just as a quick update.
While the transitioning from paper-elements to mwc is quite straight forward, although it tripples the bundle size 😢 , there are issues with importing elements such as the `ha-entity-picker` . This means that i will probably have to replace them with plain old text fields which is horrible for usability imop.
I really don't like the direction this is going.
I will still release an update tonight but be aware that it might not even look remotely as polished as before.

**Comment by JonahKr** [comment]
I released v2.5.2. which fixes the issues.
Sorry for the delay!
And thanks again for reporting the issue!
Take care and stay safe! 👍

**Comment by louis702** [comment]
It works. Good job. Thank you so much. 👍

**Comment by mdoliver** [comment]
Hi, I've been unable to get my card to work using the new release. Not sure if it's just me but I still get an unusable visual editor. 

Have downloaded the new card, restarted HA etc. Even removed the Dashboard resource and re-installed it but no joy.

core-2022.3.8
Home Assistant OS 7.6
![image](https://user-images.githubusercontent.com/51429339/161868929-787193bd-5407-416f-88c3-05fe2ed39d0a.png)

**Comment by JonahKr** [comment]
@mdoliver i created a seperate issue for you here: #107
