### ISSUE TITLE
Visual Editor issues

### ISSUE THREAD

**Issue by JonahKr** [JonahKr/power-distribution-card#107]
Hi, I've been unable to get my card to work using the new release. Not sure if it's just me but I still get an unusable visual editor. 

Have downloaded the new card, restarted HA etc. Even removed the Dashboard resource and re-installed it but no joy.

core-2022.3.8
Home Assistant OS 7.6
![image](https://user-images.githubusercontent.com/51429339/161868929-787193bd-5407-416f-88c3-05fe2ed39d0a.png)

_Originally posted by @mdoliver in https://github.com/JonahKr/power-distribution-card/issues/103#issuecomment-1089535342_

**Comment by JonahKr** [comment]
Hey there 👋 
Thanks for reporting. I am sorry but i cannot reproduce this. 🤔 
Have you tried clearing your browser cache? Home-assistant heavily relies on caching.
```
Chrome, Firefox, or Edge for Windows: Press Ctrl+F5 (If that doesn’t work, try Shift+F5 or Ctrl+Shift+R).
Chrome or Firefox for Mac: Press Shift+Command+R.
Safari for Mac: There is no simple keyboard shortcut to force a hard refresh. Instead, press Command+Option+E to empty the cache, then hold down Shift and click Reload in the toolbar.
```
Let me know if that worked for you!

Have a good one! 👍

**Comment by mdoliver** [comment]
Clearing the browser cache did the trick, sorry to waste your time!

**Comment by JonahKr** [comment]
Glad it worked 😄 Take Care!
