### ISSUE TITLE
Syntax for empty entity_id

### ISSUE THREAD

**Issue by zacchaeus80** [JonahKr/power-distribution-card#109]
Hi,

Great card.  Thanks for all your efforts.  Bit of a newbie question, but can you please confirm the syntax for adding and empty entity_id, i.e. for leaving a gap on one side?  Sorry if this is really obvious and/or I've missed it in the readme, but I've been puzzling over it for a while.

Also, it would be great if the car_charger preset were also able to take (and somehow display??)  the battery_percentage_entity property.  I'm just using the battery present for now, but it would be awesome if the car_charger could show, say, both the car icon and the battery icon with charge state.

Many thanks,

Gareth

**Comment by JonahKr** [comment]
Hey 👋 @zacchaeus80 
you just have to remove the entity_id in the UI editor like this:
![image](https://user-images.githubusercontent.com/38377070/168494024-67b3dac8-125d-4758-8283-3a804404fae4.png)

Take care and Stay safe!
