### ISSUE TITLE
Card not working on my Sensors

### ISSUE THREAD

**Issue by Vandiliz3r** [JonahKr/power-distribution-card#11]
I have created the card as per below, But not sure if i am missing something. 

**type: 'custom:power-distribution-card'
title: Overview
battery: sensor.battery_watts
home: sensor.inverter_totalwatts
solar: sensor.solar_watts
grid: sensor.gridwatts
autarky: sensor.autarky -- This i did not change do i need to do something here?
ratio: sensor.ratio -- This i did not change do i need to do something here?**

Not sure if this works with Any Solar system or just with e3DC?

**Comment by JonahKr** [comment]
Hi 👋,
This works with any sensor.
You can just remove
```yaml
autarky: sensor.autarky -- This i did not change do i need to do something here?
ratio: sensor.ratio -- This i did not change do i need to do something here?
```
this part and everything should work. Maybe you need to tweak the Arrowdirections but this bug will be fixed with the next update.

**Comment by Vandiliz3r** [comment]
Ah Sweet, Thanks man!
That worked, Now i just need to figure out the inverted values..

**Comment by JonahKr** [comment]
be aware that inverted values cahnges the value itsself and there fore affects the calculations for ratio and autarky.. 
Invert_arrows however only affects the arrows.
