### ISSUE TITLE
Is it possible to change Bar Units?

### ISSUE THREAD

**Issue by JonahKr** [JonahKr/power-distribution-card#112]
Hi, really like this card.
 Is it possible to change the units displayed above the bars. I have a water heater which has 2 entities for temperature in °C. They work really well with bars, however they are displayed as % , it would be great if I could change this  to degrees C.
Many thanks Pete

_Originally posted by @guzzit3 in https://github.com/JonahKr/power-distribution-card/issues/77#issuecomment-1246669559_

**Comment by JonahKr** [comment]
Attachment: ![Screenshot_20220914-131113_Home Assistant.jpg](https://user-images.githubusercontent.com/18375102/190150179-12a7b23e-e324-42c8-8b32-248b16fec0bc.jpg)

**Comment by JonahKr** [comment]
Hey there @guzzit3 👋
At the moment only percentage values are allowed, but I like the idea. 
I am assuming the Water Heater has a `unit_of_measurement` in `°C` right?
Thanks in advance!
Take care and stay safe 👍

**Comment by guzzit3** [comment]
I believe the entity has a choice of  °F, °C and K.
Many thanks Pete

**Comment by JonahKr** [comment]
Ok Makes sense. 
I will push a update either this evening or tomorrow. 
And thank you very much for your donation! ❤️

**Comment by guzzit3** [comment]
Thanks that's great

**Comment by JonahKr** [comment]
Hey there @guzzit3 👋
This feature is included in the latest release! If you still experience some issues, feel free to reopen the issue or create a new one.
Take care and stay safe!

**Comment by guzzit3** [comment]
![Screenshot_20220915-191725_Home Assistant.jpg](https://user-images.githubusercontent.com/18375102/190479914-79055560-2c6f-4f15-9adf-764516e206d6.jpg)

Perfect, thank you very much. Works like a charm 
Much appreciated Pete
