### ISSUE TITLE
Klick Aktion an falscher Stelle

### ISSUE THREAD

**Issue by saschaludwig** [JonahKr/power-distribution-card#116]
Hi,
in der Kartenkonfiguration toggelt das Klicken auf das Label "Namen ersetzen" die Checkbox von "Invertierter Wert"

<img width="357" alt="Bildschirm­foto 2022-11-22 um 01 31 41" src="https://user-images.githubusercontent.com/12997980/203185678-fe494b21-8542-4bc9-be2f-9371658afe5d.png">

**Comment by JonahKr** [comment]
Hallo 👋 
Vielen Dank für die Meldung. Ich konnte das ganze jetzt leider nicht replizieren.
Vielleicht hat es was mit den unsichtbaren Feldern, die bis zum heutigen Update nichtmehr geladen wurden, allerdings kann ich mir das kaum Vorstellen.
Vielleicht könntest du das Update installieren und schauen, ob das Problem dann immernoch besteht?
Danke im vor aus!👍

**Comment by saschaludwig** [comment]
Hi, auch nach Update ist der Bug noch da.
Getestet auf MacOS 12.2.1 + Safari 15.3 + Chrome 107.0.5304.110 + Firefox 107.0

Hier ein Video davon:

https://user-images.githubusercontent.com/12997980/203356360-ae473c2f-557e-4e53-829d-c89bb43f1420.mov

**Comment by JonahKr** [comment]
Ah entschuldige. Ich habe nur auf die Box gedrückt. Ich hab das Problem gefunden und werde sofort die neue Version publishen.
Vielen herzlichen Dank zudem für die Spende! 😄
