### ISSUE TITLE
Arrows now display over the top of the W label

### ISSUE THREAD

**Issue by Siggy101** [JonahKr/power-distribution-card#119]
I just installed v2.5.6. and found a little bug.
The smooth scrolling arrows now flow over the top of the W (Watts) label.  Do you think you could fix pls?
Here is an example.  Look at the bottom left item called "Office".  The W is hidden behind the arrows.
NB:  This only happens when the number has something over the decimal place so it flows onto 2 lines instead of the usual 1 line.

![image](https://user-images.githubusercontent.com/41893936/203567185-f64f413d-4a83-4749-8a6a-43e5faebf554.png)

**Comment by JonahKr** [comment]
Hey there 👋 
Thanks for the Report and good catch! Should be an easy fix but sadly i won't have time for until next week.
Take care! 👍

**Comment by Siggy101** [comment]
No rush at all.  It is a real corner case and not a biggie.
Thanks for having a look whenever you have the time.

**Comment by dagra68** [comment]
Hi! I have a similar issue 
![image](https://user-images.githubusercontent.com/99665350/222178069-157ab23b-b559-40d9-95a1-c77eb605bb88.png)

**Comment by JonahKr** [comment]
Fixed in the latest release. Take care! 👍
