### ISSUE TITLE
Home Sensor Positive Value

### ISSUE THREAD

**Issue by Vandiliz3r** [JonahKr/power-distribution-card#12]
Hi Again,

There seems to be a calulation error on the Autarky and Ratio value when i change my Home sensor value to inverted.
![image](https://user-images.githubusercontent.com/48084630/95205173-4d41df80-07e5-11eb-9001-c95a52a5da74.png)

Just thought that it would be great to cater for this because if i do not change to inverted it looks like my home is give power not receiving 👍 
![image](https://user-images.githubusercontent.com/48084630/95205342-88441300-07e5-11eb-91d8-e7371e1dfd26.png)

Regards

**Comment by JonahKr** [comment]
So... as stated in README.md : 
Negative Values equal to consumption
Positive Values equal to production... 
Therefore check if your sensor applies to these ground rules and if it does then only change the arrows direction (`invert_arrow`) but do not invert the value.

**Comment by JonahKr** [comment]
Furthermore a issue regarding the calculation is already open here: https://github.com/JonahKr/power-distribution-card/issues/8

**Comment by Vandiliz3r** [comment]
Again!!!! Thanks man!! Should have checked that inverted arrow function!!!
