### ISSUE TITLE
Action Editor not visible with 2022.12

### ISSUE THREAD

**Issue by JonahKr** [JonahKr/power-distribution-card#121]

**Comment by JonahKr** [comment]
The only long term viable solution would be to rewrite the whole editor to use the `ha-form` element.
Since i don't think that this is a 30min fix, this will be postponed until end of dec.

**Comment by funracer900** [comment]
Hi, 
I've the same issue with 2023.3.1/3.2/3.3.
Will there be a fix in Sight?
Greetings

**Comment by JonahKr** [comment]
Hi there 👋 @funracer900 
I know how to fix it but don't have the time at the moment.
The same for alot of the other issues although i was able to fix some already in the dev branch.
I cannot give you an eta but i guess with the next release of version `2.5.8` or `3.0.0`depending on the further changes this will be resolved.

**Comment by funracer900** [comment]
Ok, thanks for fast Response.

**Comment by JonahKr** [comment]
Fixed in the latest release. Take care! 👍
