### ISSUE TITLE
Suggestion - autarky / ratio wording

### ISSUE THREAD

**Issue by gregpetersau** [JonahKr/power-distribution-card#122]
I could be wrong in my interpritation, but i think autarky = self-sufficiency.  [what percent of your consumption was from solar, eg how 'off-grid you are'
&  ratio = self-consumption   [what percent of your energy did you use vs export back to the grid]

These are the terms used in english (at least in Australia for these concepts)

Suggestion (if i am correct) to add something like this in documentation for those who may have been confused.

Just downloded and installed, fantastic card, good work!

**Comment by JonahKr** [comment]
Hey there 👋 
Glad you like it!
The explanation for it can be found here: https://github.com/JonahKr/power-distribution-card#what-the-heck-are-these-autarky-and-ratio-calculating
Or alternatively it has been discussed in past issues or is documented in code: https://github.com/JonahKr/power-distribution-card/blob/2232830e34cfb51385dd5b4dbfa9a92b79e3f084/src/power-distribution-card.ts#L480-L489

I'll probably extend the explanation in the FAQ section of the docs to make it more clear.
Thanks for your suggestion! 👍
