### ISSUE TITLE
Add Battery SOC displaying

### ISSUE THREAD

**Issue by Vandiliz3r** [JonahKr/power-distribution-card#13]
Good Day Again,

Would be great if you could build in the battery SOC sensor that then changes the icon the more depleted it becomes where you can specify the % you would like it to be red/orange/green.

Example
battery: 
   entity: sensor.e3dc_battery
   soc: sensor.battery_soc
   color:
      green: 80
      orange: 50
      red: 30

Would also be great if you can show the % under the battery image on the card :)
Might be wishful thinking.

**Comment by JonahKr** [comment]
To Include the ideas from https://github.com/JonahKr/power-distribution-card/issues/14 :
Additionally the SOC should be displayable in percent...

More ideas are a change of icon based on the ones already delivered with [mdi](https://cdn.materialdesignicons.com/5.4.55/)

**Comment by JonahKr** [comment]
Ok just as a update and for clarification:
- The Icon color already can change on +/-/0 values.
- with https://github.com/JonahKr/power-distribution-card/commit/446b2497c3d078213d870e11582ade2dd00ab833 you can now specify a secondary info at the right side from the icon.
- 
I don't want to overcomplicate it and think this kind of fulfils this request. If you are missing something specific just create a new issue.
Take Care and stay safe 👍
