### ISSUE TITLE
Card usage, some tweaks and suggestions

### ISSUE THREAD

**Issue by Lateadapter** [JonahKr/power-distribution-card#131]
Hi,
first of all many thanks for that very usefull card. We own a system from E3DC and the card fits very well to our needs.
Following I want share my setup and some tweaks which might be usefull for others as well.
I have done following dedicated configurations:
1.	adding a background picture
2.	adding daily-energie-entities as secondary information
3.	using the center „card“ configuration and adding money-entities for daily energy purchase and solar earnings
4.	tweak for battery-SOC arrows

The card was mainly configured for mobile usage. 

![image](https://user-images.githubusercontent.com/122560017/224496828-7b5b4223-52cd-407c-8ba7-30a894aebd13.png)
![image](https://user-images.githubusercontent.com/122560017/224496855-e198fa17-a415-4a43-a8df-7ebb3c7a30bd.png)

# 1. adding a background picture
The picture is a png with removed background.
Precondition for card implementation is the already installed card-mod plugin by Thomas Loven:
https://github.com/thomasloven/lovelace-card-mod
sample code (to be added at end of YAML-code):

```
card_mod:
  style: |
    ha-card {
      background: url('/local/E3DC_Pro.png');
      background-size: 350px 420px;
      background-position-x: center;
      background-position-y: -50px;
      background-repeat: no-repeat;
      background-color: var(--card-background-color);
      }
```
After adjusting size and position  the  two last lines are required to avoid multiple picture implementation (if the original picture size not exactly fits the space) and to bring back the disappeared card-background-color. Actual it could be used any color, however adding the global variable will adjust the view automatically for dark and light theme.
Following screenshot shows the result without mentioned two lines (missing dark-gray card-color and repeated picture part):

![image](https://user-images.githubusercontent.com/122560017/224497435-e9335698-8931-4184-8a31-8dfc01a337a6.png)

# 2. adding daily-energie-entities as secondary information
All the data from E3DC System I collect via Mod-Bus within a Node-Red integration. But all entities only supply power numbers (W), which are used in the card as primary data showing the energy flow. In order to calculate the real consumed resp. produced energy I use HA helpers:

  -    helper „Riemann Integration“ for calculating the total energy of an entity 
please note: 
the control electronics of the E3DC system sometime generates some power spikes over few seconds, which are resulting in huge energy numbers after „Riemann  Integration“ based on „kWh“; workaround: setting Mod-Bus polling time on small number 
(i.e. 2 sec), doing „Riemann Integration“ on base of „kWs“, building a new entity containing the final calculated number in kWh (in my case I also use Node-Red)
  -	helper „consumtion counter“ to get the „daily energy“ to be used as „secondary info“ in the card + „replace name“
  -	for few consumers I realized that the shown precision is not controlled by the „precision parameter“ of the power-distribution- 
        card. Although in Home Assistant 2023.3.1 was introduced the possibility to overwrite the precision of each entity, it doesn’t work 
        with „consumtion counter“ and this card here. In order to overcome that issue I defined for required cases additional helper of 
        type „condition combination of sensors“ and did use as input just the only one „consumtion counter“ with output median and 
        choosen precision.
![image](https://user-images.githubusercontent.com/122560017/224502721-0fa4df19-5b3e-4e4b-945e-498dd7960b9e.png)

# 3. center „card“ configuration 
For money-entities again I used Node-Red for calculation and sensor-definition.
Via the above mentioned card-mod plugin it’s possible to place and adjust two entities within the existing space.
sample code:

```
center:
  type: card
  content:
    type: grid
    square: false
    columns: 1
    cards:
      - type: custom:mushroom-entity-card
        entity: sensor.tageskosten_strom
        name: Bezug
        fill_container: false
        icon: mdi:currency-eur
        icon_color: red
        secondary_info: name
        primary_info: state
        layout: vertical
        card_mod:
          style: |
            ha-card {
              position: absolute;
                top: 50%;
                left: 43%;
                }
      - type: custom:mushroom-entity-card
        entity: sensor.tagesertrag_solarstrom
        icon: mdi:currency-eur
        icon_color: amber
        name: Ertrag
        secondary_info: name
        primary_info: state
        layout: vertical
        card_mod:
          style: |
            ha-card {
              position: absolute;
                top: 70%;
                left: 43%;
                }

```
# 4. tweak for battery-SOC arrows
For showing the battery-SOC number originally I switched off the „arrow“ functionality.
However in the view on smartphone that was resulting in vertical misalignment of shown entities:

![image](https://user-images.githubusercontent.com/122560017/224503045-7a992c66-d85a-4685-a27e-2daf6b8740a1.png)

That behavior differs from PC-view, where entities and arrows are placed side by side (as reference below; but here you can also see the graphical mismatch of my setup in the center what actual I don’t care)

![image](https://user-images.githubusercontent.com/122560017/224503070-889b118b-4b59-46bf-ad99-b1b59e11fa1d.png)

What I did is, that I defined the color of arrows like the background color „var(--card-background-color)“ and reactivated the arrows. Now the arrows are there requiring there space, however not visible.

![image](https://user-images.githubusercontent.com/122560017/224503098-2d2ccc6d-d93f-4c42-aa02-bfa67b9d9d15.png)

![image](https://user-images.githubusercontent.com/122560017/224503111-6d4daa4f-86db-464b-960f-612dc899ace1.png)

# few suggestions
Based on current experiences I would have following suggestions for further card development:
- include precision control for secondary info
- enlarge the middle color threshold to a range (i.e. for defining three different colors for battery-SOC)
- possibility to hide (or recolor) the number of primary entity (originally my idea was to write the SOC-percentage as secondary info instead of the name and nothing at the place of arrows, but that is not possible; the hiding of the number itself would be possible by choosing an alternative attribute, but than the color threshold doesn’t work anymore)

**Comment by c0r32quad** [comment]
Hello,

Just a quick addition from me, since I wanted to adjust the color of the value frames to match those of the original card.

Center card:
```

center:
  type: card
  content:
    type: custom:button-card
    entity: sensor.strom_hausverbrauch
    name: Home
    icon: mdi:home
    show_icon: true
    show_name: true
    show_state: true
    styles:
      card:
        - width: 110px
        - height: 110px
        - background: var(--card-background-color)
        - position: relative
        - display: flex
        - align-items: center
        - justify-content: center
        - overflow: hidden
      grid:
        - grid-template-areas: "\"i\" \"n\" \"s\""
        - justify-items: center
        - align-items: center
    custom_fields:
      ring: |
        [[[
          const solar = Number(states['sensor.shellyplus1pm_solar_power']?.state || 0);
          const grid = Number(states['sensor.esp32_strom_hauptzaehler_aktuelle_leistung']?.state || 0);
          const total = solar + grid;

          let solarPct = total > 0 ? (solar / total) * 100 : 0;
          solarPct = Math.max(0, Math.min(100, solarPct)); // begrenzen
          const gridPct = 100 - solarPct;

          // runden auf ganze Zahlen
          const solarPctRounded = Math.round(solarPct);

          return `
            <div style="
              position: absolute;
              inset: 0;
              border-radius: 1em;
              padding: 5px; /* Abstand zum inneren Inhalt */
              background: conic-gradient(
                #ff9800 0% ${solarPct}%,
                #488fc2 ${solarPct}% 100%
              );
              z-index: 0;
            ">
              <div style="
                width: 100%;
                height: 100%;
                background: var(--card-background-color);
                border-radius: 0.9em;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
              ">
                <ha-icon icon='mdi:home' style='width:24px; color: var(--state-icon-color)'></ha-icon>
                <div style='font-family: var(--ha-font-family-body); font-size: var(--ha-font-size-m); font-weight: var(--ha-font-weight-normal); line-height: var(--ha-line-height-normal);'>
                  ${states['sensor.strom_hausverbrauch'].state} W
                </div>
                <div style="
                  font-family: var(--ha-font-family-body);
                  font-size: 11px;
                  font-weight: var(--ha-font-weight-normal);
                  line-height: var(--ha-line-height-normal);
                ">
                  ${solarPctRounded}% / ${100-solarPctRounded}%
                </div>
              </div>
            </div>
          `;
        ]]]
```

Card mod for the borders:

```
card_mod:
  style: |
    /* left container – top  (Solar 1) */
    ha-card > div > div:nth-child(1) > item:nth-child(1) > badge {
      border: 2.5px solid
        {% if states('sensor.kostal_plenticore_solar_power')|float > 1 %}
          #ff9800   /* orange when value is greater than 0*/
        {% else %}
          rgb(72, 72, 74)   /* gray if 0 */
        {% endif %};
    }
    /* left container – bottom (Solar 2) */
    ha-card > div > div:nth-child(1) > item:nth-child(2) > badge {
      border: 2.5px solid
        {% if states('sensor.shellyplus1pm_solar_power')|float > 1 %}
          #ff9800   /* orange when value is greater than 0*/
        {% else %}
          rgb(72, 72, 74)   /*  gray if 0 */
        {% endif %};
    }
    /* right container – top (Netz) */
    ha-card > div > div:nth-child(3) > item:nth-child(1) > badge {
      border: 2.5px solid
        {% if states('sensor.esp32_strom_hauptzaehler_aktuelle_leistung')|float > 0 %}
          #488fc2   /* Blue by consuming*/
        {% else %}
          #8353d1   /* Purple when feeding into the grid */
        {% endif %};
    }
    /* right container – bottom (battery) */
    ha-card > div > div:nth-child(3) > item:nth-child(2) > badge {
      border: 2.5px solid
        {% if states('sensor.kostal_plenticore_battery_power')|float == 0 %}
          rgb(72, 72, 74)   /* ray if 0 */        
        {% elif states('sensor.kostal_plenticore_battery_power')|float > 0 %}
          #f06292   /*Pink when charging*/
        {% else %}
          #4db6ac   /*Turquoise when discharging */
        {% endif %};
    }
```

<img width="365" height="275" alt="Image" src="https://github.com/user-attachments/assets/c74b08ad-f32c-4c64-b3d8-8a60be81948a" />
