### ISSUE TITLE
Feature request: Last updated

### ISSUE THREAD

**Issue by Jurgen1980** [JonahKr/power-distribution-card#141]
Add field for last modified
![image](https://user-images.githubusercontent.com/45353259/229351312-362114f8-75d4-496f-a0b4-2b467b347806.png)

**Comment by JonahKr** [comment]
Hi there 👋 
What is it exactly you want to achieve?
Just a text beneath the card? 
In that case you could just use a vertical stack card with this card in the top part and a Markdown card in the lower.
If you want to check for the last update of any given sensor, i would recommend a template sensor which is easily implementable with the help of the UI editor. 
Take care! 👍

**Comment by JonahKr** [comment]
Hi again,

Since this seem to be stale, i am going to close the issue.
If you require some help with the template sensor or the card stacking, the homeassistant discord will be able to help you or alternatively reopen this issue.

Take care and stay safe!
