### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by hjschwe** [JonahKr/power-distribution-card#148]
If I use my notebook (Linux Mint 21.2), the card does not working. Only the yaml appears on the HA dashbord. I am trying FF, Chrome and cromium.
If I start windows (10 or 11) everythings work fine. Also on iOS.

What's wrong with linux? Any ideas?

RE
hjs

**Comment by JonahKr** [comment]
Hi,
Are you using the same browser on all Operating-Systems?
Can you take a look in the browser console maybe and see if there are any errors?
That would maybe give me something to work with.

Take care and stay safe!

**Comment by hjschwe** [comment]
Yes, Firefox with the latest update on Linux, Windows and iOS. I have started a fresh FF on linux without any ad ons and so one. Same error!  

Open the HA server site.
Open the error log. see below


NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart]
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.sys.mjs:1652
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.sys.mjs:1760
    BG_observe resource:///modules/BrowserGlue.sys.mjs:1023
    _delayedStartup chrome://browser/content/browser.js:2055
BrowserGlue.sys.mjs:1661:15
Experiment next-generation-accessibility-engine-powering-screen-readers has unknown featureId: accessibilityCache RemoteSettingsExperimentLoader.sys.mjs:596:21
Experiment next-generation-accessibility-engine-powering-screen-readers-and-other-ats-copy has unknown featureId: accessibilityCache 2 RemoteSettingsExperimentLoader.sys.mjs:596:21
LoginHelper(Main): Couldn't parse specified uri about:policies with error NS_ERROR_FAILURE LoginHelper.sys.mjs:693:18
Das Cookie "" wurde als Drittanbieter abgelehnt. event.png
Das Cookie "" wurde als Drittanbieter abgelehnt. csi
Das Cookie "" wurde als Drittanbieter abgelehnt. event.png
Das Cookie "" wurde als Drittanbieter abgelehnt. event.png
Das Cookie "" wurde als Drittanbieter abgelehnt. csi
Das Cookie "" wurde als Drittanbieter abgelehnt. csi
Das Cookie "" wurde als Drittanbieter abgelehnt. csi
Das Cookie "" wurde als Drittanbieter abgelehnt. iev
Das Cookie "" wurde als Drittanbieter abgelehnt. iev
Missing resource in locale de: devtools/client/toolbox.ftl

**Comment by JonahKr** [comment]
What about the browser console?
![grafik](https://github.com/JonahKr/power-distribution-card/assets/38377070/b1cad78f-8a6c-4eff-89bd-90b2314038ec)

Your error log seems to be related with virtualbox and not with homeassistant.

**Comment by JonahKr** [comment]
> Problem solved. I have started a new download from the card. Now I can see the card with my settings! Sorry for confusion.

Got Your reply a second to late 😅 
Take care and let me know if something comes up again!
