### ISSUE TITLE
tap_action or double_action: navigate

### ISSUE THREAD

**Issue by cddu33** [JonahKr/power-distribution-card#149]
Hi thanks for this card.

When I click on action / navigate on an entities, the script create this:
 `    tap_action:
      undefined:
        undefined: {}`

so you have to edit the yaml by hand for exemple:
` tap_action:
      action: navigate
      navigation_path: /energy`

**Comment by neotigger** [comment]
Only 2 undefined, then you are still good, I already had chains of at least 5.
Only manual processing helps

**Comment by JonahKr** [comment]
Hey there @cddu33 👋 
Thanks alot for the report. I fixed and it will be patched in the next release.

@neotigger Sorry that this was your experience. If you encounter issues or bugs, please consider reporting them so i can take a look at them earlier!

Take care and stay safe! 👍
