### ISSUE TITLE
If the autarky croses up 100% the bar is over the number

### ISSUE THREAD

**Issue by Oxgit** [JonahKr/power-distribution-card#153]
If the autarky croses up 100% the bar is over the number.
There could be two options for solution:
1) autarky limited to 100% cap
2) the bar is displayed under the number to show the value

**Comment by JonahKr** [comment]
Hey there 👋 
Could you maybe provide a picture of this occuring?
This actually shouldn't be possible, unless you are providing the autarky value yourself, as seen here:
https://github.com/JonahKr/power-distribution-card/blob/6faf5f4ac3ad82106b43267347e45c4fbbdcb043/src/power-distribution-card.ts#L484-L487

Thanks in advance!

**Comment by Oxgit** [comment]
I'm  providing it myself - that's true

![image](https://github.com/JonahKr/power-distribution-card/assets/67378707/f20e8ce0-cf56-48c8-9d97-26e37a851921)

**Comment by JonahKr** [comment]
Fixed with https://github.com/JonahKr/power-distribution-card/releases/tag/v2.5.11

**Comment by Oxgit** [comment]
Thank you
