### ISSUE TITLE
Placeholder entry causes card to 'disappear'

### ISSUE THREAD

**Issue by jaymunro** [JonahKr/power-distribution-card#154]
Add a placeholder as per docs (just hit the plus to add a blank entity).
```
Placeholder
By submitting an empty entity_id and preset, you will generate a plain transparent placeholder item which can be used to further customize your layout.
```

Then hit save and the card is not shown.
Hit Edit and remove the blank entity and the card is restored.

<img width="507" alt="Screenshot 2023-11-03 at 8 16 54 PM" src="https://github.com/JonahKr/power-distribution-card/assets/1166024/c3702c17-1388-4a4f-a2bf-708b03362cee">

<img width="971" alt="Screenshot 2023-11-03 at 8 14 28 PM" src="https://github.com/JonahKr/power-distribution-card/assets/1166024/a80dbe36-78f7-4686-9979-c55a1afc35c0">

<img width="549" alt="Screenshot 2023-11-03 at 8 16 00 PM" src="https://github.com/JonahKr/power-distribution-card/assets/1166024/693cbf46-9371-4128-a473-7970a27e1ba1">

**Comment by JonahKr** [comment]
Thanks for the report. I will take a look at this this weekend.

Take care and stay safe!👍

**Comment by JonahKr** [comment]
Ok i was able to confirm this.
This is related if you just add an empty entity without specifying the "placeholder" preset.
Should be a relatively easy fix but i am quite packed at the moment.

**Comment by jaymunro** [comment]
Ah, I didn’t realise there was a “Placeholder” preset. This can be resolved just by changing the Read.Me instruction from
```
Placeholder
By submitting an empty entity_id and preset, you will generate a plain transparent placeholder item which can be used to further customize your layout.
```
To
```
Placeholder
By submitting a “Placeholder” preset and no entity ID, you will generate a plain transparent placeholder item which can be used to further customize your layout.
```

**Comment by JonahKr** [comment]
Fixed with https://github.com/JonahKr/power-distribution-card/releases/tag/v2.5.11
