### ISSUE TITLE
Doesn't seem to work on a dashboard on an older iPad ?

### ISSUE THREAD

**Issue by Duff-Box1** [JonahKr/power-distribution-card#156]
Works fine on newer iPads. But stopped working this morning after latest core upgrade on my older iPad. 
Photo attached.

https://github.com/JonahKr/power-distribution-card/assets/56402252/dbf729b8-82f2-44fc-bc5a-07cecf928b27

**Comment by JonahKr** [comment]
Hi there @Duff-Box1 
I know there has been a homeassistant folder migration from "/config" to "/homeassistant".
Could you maybe try to uninstall the card and reinstall it via the hacs interface?
Take care and stay safe! 👍

**Comment by JonahKr** [comment]
Considering it doesn't work only on your older one, i would suspect it has somethign to do with the browser not loading the files.
I am not all to familiar with safari, but maybe you could "hard refresh" it aswell?

**Comment by Duff-Box1** [comment]
Hi would it be that if it works perfectly with the same dashboard on my newer iPad and iPhone? Seems like it’s my old iPad that won’t render the card?Perhaps my old iPad doesn’t support some of the code in the card? Would that be likely?Many thanksSent from my iPadOn 11 Nov 2023, at 11:18, JonahKr ***@***.***> wrote:﻿
Hi there @Duff-Box1
I know there has been a homeassistant folder migration from "/config" to "/homeassistant".
Could you maybe try to uninstall the card and reinstall it via the hacs interface?
Take care and stay safe! 👍

**Comment by Duff-Box1** [comment]
Ok will try that. I think in both cases the dashboard is using the home assistant App I think. I will try the reboot of the old iPad.Sent from my iPadOn 11 Nov 2023, at 11:20, JonahKr ***@***.***> wrote:﻿
Considering it doesn't work only on your older one, i would suspect it has somethign to do with the browser not loading the files.
I am not all to familiar with safari, but maybe you could "hard refresh" it aswell?

**Comment by Duff-Box1** [comment]
I realised the HA App was not up to date, so updated and rebooted iPad but unfortunately it doesn’t work, so it looks like I will have to use some other power card or upgrade the wall iPad! The iOS is frozen on that iPad at 12.5.7 the iPad Air is the original air from 2013, it was a useful wall display but probably time to upgrade!Thanks Sent from my iPadOn 11 Nov 2023, at 11:20, JonahKr ***@***.***> wrote:﻿
Considering it doesn't work only on your older one, i would suspect it has somethign to do with the browser not loading the files.
I am not all to familiar with safari, but maybe you could "hard refresh" it aswell?

**Comment by JonahKr** [comment]
Hm... Out of curiosity. Do you have any other custom cards isntalled which stopped to work?
Are there any log entries?
I don't think it would be worth replacing a fully functioning ipad to be honest.

**Comment by Duff-Box1** [comment]
Hi no just this card has the issue. Here is the log entry:Logger: frontend.js.es5.202310302Source: components/system_log/__init__.py:300First occurred: 09:49:20 (9 occurrences)Last logged: 11:51:31Uncaught error from WebKit 605.1.15 on iOS 12.5.7 InvalidStateError: Cannot instantiate a custom element inside its own constructor during upgrades construct ([native code]::) y (src/scoped-custom-element-registry.js:173:6) construct ([native code]::) Super ***@***.***/runtime/helpers/esm/createSuper.js:11:33) r (src/reactive-element.ts:930:4) construct ([native code]::) Super ***@***.***/runtime/helpers/esm/createSuper.js:11:33) n (src/lit-element.ts:115:) construct ([native code]::) Super ***@***.***/runtime/helpers/esm/createSuper.js:11:33)Sent from my iPadOn 11 Nov 2023, at 12:10, JonahKr ***@***.***> wrote:﻿
Hm... Out of curiosity. Do you have any other custom cards isntalled which stopped to work?
Are there any log entries?
I don't think it would be worth replacing a fully functioning ipad to be honest.

**Comment by JonahKr** [comment]
I asked in the homeassistant channels for some information regarding rendering in the iOs app and will get back to you once i know more. In the meantime i am sorry for the inconvenience.

**Comment by Saentist** [comment]
@Duff-Box1 this is a problem of browser engine and a way he use memory
same situation with LG WebOS

Maby is connected with Java container on embedded/portable device's, 
with are limited to 256 or less Mb total ram usage

**Comment by Duff-Box1** [comment]
Thank you,  in the end I just swapped the old iPad wall display for a newer generation which fixed the issue. Cheers Sent from my iPhoneOn 17 Dec 2023, at 13:56, Saentist ***@***.***> wrote:﻿
@Duff-Box1 this is a problem of browser engine and a way he use memory
same situation with LG WebOS
Maby is connected with Java container on embedded/portable device's,
with are limited to 256 or less Mb total ram usage

**Comment by JonahKr** [comment]
Sadly, I haven't received any feedback from the homeassistant team.
It would be good to know if the thing that broke it was a homeassistant core or custom card update.
Additionally, console logs would be beneficial in getting to the bottom of this, although I am unsure how to retrieve them for either of your devices.
Probably in the end, it will have to do with some library or polyfill missing, for which I could release an "old" version.
I generally try to keep the main branch of the card up to date to comply with security advisories, so this wouldn't receive any new development then.

**Comment by JonahKr** [comment]
I think this has to do with the change from lit 2 to lit 3, which turns out, also dropped support for IE11.

I added a prerelease version [v2.5.12](https://github.com/JonahKr/power-distribution-card/releases/tag/v2.5.12), which you can download from HACS as described here: https://hacs.xyz/docs/faq/beta/
You'll need to redownload the card and enable beta releases.

I would love to hear some feedback on if this resolved the issue.

Take care! 👋

**Comment by simonstamm** [comment]
Awesome - it actually works now again with v2.5.12. Much appreciated!

**Comment by JonahKr** [comment]
Nice! I will change the version to full release then. Thanks for the TV OS hint, that's what brought me on the right track.
Take care everyone and stay safe! ❤️

**Comment by Duff-Box1** [comment]
Thanks for resolving. Unfortunately I gave away my old iPad so can’t try it and give you some feedback.Great work thanks.Sent from my iPhoneOn 5 Jan 2024, at 22:23, JonahKr ***@***.***> wrote:﻿
Nice! I will change the version to full release then. Thanks for the TV OS hint, that's what brought me on the right track.
Take care everyone and stay safe! ❤️

**Comment by Saentist** [comment]
Work on my iPad mini 2
but not on my LG

Guess problem is totally in HA way to load resources.
All JS and fonts used in initial loading, no matter is they displayed in current screen,
in my case 114Mb of data.

**Comment by JonahKr** [comment]
Thanks for the info @Saentist 
At least older iPads seem to work now 😅.
The total size of this card is ~150kb which is significantly less than a normal picture, so I assume the impact to be negligible.
