### ISSUE TITLE
Problem ratio 100%

### ISSUE THREAD

**Issue by schumissimo63** [JonahKr/power-distribution-card#157]
Hello I use your plugin which is really very good, thank you for your work!!!
I encounter a problem, whatever I do my ration remains at 100%, where is my error, after multiple tests and research I have not found it.

Thanking you in advance for your help.

`type: custom:power-distribution-card
title: Title
entities:
  - decimals: 2
    display_abs: true
    name: Maison
    unit_of_display: kWw
    consumer: true
    icon: mdi:home
    entity: sensor.conso_energie_jour
    preset: consumer
    invert_value: true
  - decimals: 2
    display_abs: true
    name: Import
    unit_of_display: kWw
    icon: mdi:transmission-tower
    entity: sensor.energie_importee_jour
    preset: grid
    invert_value: false
    calc_excluded: false
  - decimals: 2
    display_abs: true
    name: Solaire
    unit_of_display: kWw
    icon: mdi:solar-power
    producer: true
    entity: sensor.prod_solaire_jour
    preset: solar
    calc_excluded: false
  - decimals: 2
    display_abs: true
    name: Export
    unit_of_display: kWw
    icon: mdi:lightning-bolt-outline
    producer: true
    entity: sensor.energie_exportee_jour
    preset: producer
    invert_value: true
    calc_excluded: false
center:
  type: bars
  content:
    - preset: autarky
      name: AS
      bar_color: red
    - preset: ratio
      name: Ratio
      bar_color: green
animation: flash
![2023-12-21_122431](https://github.com/JonahKr/power-distribution-card/assets/76776295/2848530b-6360-4ab4-91c7-0bfeba157818)
`

**Comment by schumissimo63** [comment]
> Hello I use your plugin which is really very good, thank you for your work!!! I encounter a problem, whatever I do my ration remains at 100%, where is my error, after multiple tests and research I have not found it.
> 
> Thanking you in advance for your help.
> 
> `type: custom:power-distribution-card title: Title entities:
> 
> * decimals: 2
>   display_abs: true
>   name: Maison
>   unit_of_display: kWh
>   consumer: true
>   icon: mdi:home
>   entity: sensor.conso_energie_jour
>   preset: consumer
>   invert_value: true
> * decimals: 2
>   display_abs: true
>   name: Import
>   unit_of_display: kWh
>   icon: mdi:transmission-tower
>   entity: sensor.energie_importee_jour
>   preset: grid
>   invert_value: false
>   calc_excluded: false
> * decimals: 2
>   display_abs: true
>   name: Solaire
>   unit_of_display: kWh
>   icon: mdi:solar-power
>   producer: true
>   entity: sensor.prod_solaire_jour
>   preset: solar
>   calc_excluded: false
> * decimals: 2
>   display_abs: true
>   name: Export
>   unit_of_display: kWh
>   icon: mdi:lightning-bolt-outline
>   producer: true
>   entity: sensor.energie_exportee_jour
>   preset: producer
>   invert_value: true
>   calc_excluded: false
>   center:
>   type: bars
>   content:
>   
>   * preset: autarky
>     name: AS
>     bar_color: red
>   * preset: ratio
>     name: Ratio
>     bar_color: green
>     animation: flash
>     ![2023-12-21_122431](https://private-user-images.githubusercontent.com/76776295/292187144-2848530b-6360-4ab4-91c7-0bfeba157818.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjAzMjAsIm5iZiI6MTcwMzE2MDAyMCwicGF0aCI6Ii83Njc3NjI5NS8yOTIxODcxNDQtMjg0ODUzMGItNjM2MC00YWI0LTkxYzctMGJmZWJhMTU3ODE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEyMDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMmMwZGZmYTU1ZDI0MGZhMWJiN2JjMTZlN2EyNjMyNjUyMmU0YTc3YmMwZjE2OGQzZjYwMDQzNTZkY2QxMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.licxc6YsYLJ2yzLhZ4JPUl17Nk9ZnnIIdjgSRWFPysM)
>     `

**Comment by schumissimo63** [comment]
Everything works very well, I misinterpret the ratio in the card. Thank you again for your wonderful work.

**Comment by JonahKr** [comment]
Glad you're enjoying it!
Just to write it down in case someone stumbles over this in the future:
The Ratio measures the proportion of self produced Energy used at home. 
Since in this case 2,8 < 11,4 the ratio is 100%, since all of the produced power would be consumed by the home.

Take care and stay safe!
