### ISSUE TITLE
Move columns closer together

### ISSUE THREAD

**Issue by allseven** [JonahKr/power-distribution-card#160]
I don't have anything occupying the centre area so the two columns are quite far apart. Is it possible to implement a way to move them closer to each other?

**Comment by neotigger** [comment]
With Card-Mod via HACS

card_mod:
  style: |
    .card-content {
    grid-template-columns: 1fr 0px 1fr!important;
    }

**Comment by allseven** [comment]
Thanks, that worked a treat!

**Comment by JonahKr** [comment]
Thanks, @neotigger  for stepping in and providing a solution!
