### ISSUE TITLE
invert arrow

### ISSUE THREAD

**Issue by 1achy** [JonahKr/power-distribution-card#162]
Is it possible make if respect entity direction enrgy for invert battery arrow?

**Comment by JonahKr** [comment]
Hi there,
I sadly don't understand what you are asking. 
I can highly recommend using Deepl as a translator or give me more context of what you are trying to achieve.
Take care!

**Comment by 1achy** [comment]
I would like to reverse the battery energy flow arrows. I have an entity that gives me the charging and discharging of the battery and based on this entity I would like to change towards arrows


example:

  - decimals: 2
    display_abs: true
    name: home
    unit_of_display: W
    consumer: true
    icon: mdi:home-assistant
    entity: sensor.esolar_totalloadpower
    preset: home
    **invert_arrow: true**


i want some like this:

  - decimals: 2
    display_abs: true
    name: home
    unit_of_display: W
    consumer: true
    icon: mdi:home-assistant
    entity: sensor.esolar_totalloadpower
    preset: home
    invert_arrow: if (sensor-direction_Batt,"Charging", true) else (false)

i dont know us make this

**Comment by 1achy** [comment]
This is correct :?

invert_arrow: {%- set sensor = states('sensor.esolar_batterydirection') %} {%- if sensor == 'Charging' %}True {%- elif sensor == 'Standaby' %}0 {%- else %}false {%- endif %}

**Comment by JonahKr** [comment]
Ah ok i see what you are trying to do.
Sadly the yaml parsing for card configurations doesn't support jinja templates that I am aware of.
However, there should be a relatively easy solution for this by utilizing helpers.

1. Go to the Helpers tab and create a new Template sensor:
[![Open your Home Assistant instance and show your helper entities.](https://my.home-assistant.io/badges/helpers.svg)](https://my.home-assistant.io/redirect/helpers/)

2. Fill out the necessary information which should roughly like this:
![grafik](https://github.com/JonahKr/power-distribution-card/assets/38377070/21d14063-31ad-4a23-a4da-398041cc37bc)
with the following State template:
```jinja
{% if is_state('sensor.esolar_batterydirection', 'Charging') %}
  {{  states('sensor.esolar_totalloadpower') | int * -1}}
{% else %}
  {{ states('sensor.esolar_totalloadpower') | int}}
{% endif %}
```

3. Afterwards you can just use your new helper sensor as the entity for the tile.

Hope this helps!

**Comment by 1achy** [comment]
VERY VERY tks ;)
