### ISSUE TITLE
How to read the two bar's percentages.

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#18]
I have been trying to understand the percentage for the ratio, and the autarky.

When the solar system produces more electricity than is used, and the overflow is sent to the Grid, the two percentages make sense, as the ratio is 100% and the autarky states the percentage sent to Home.

OK, now the solar system is producing less than is used, and the Overview looks like this:

![overview](https://user-images.githubusercontent.com/3110308/95470350-fb35c100-0980-11eb-9973-4afb63435851.JPG)

Here I can simply not figure out what the percentages are saying...

I would be happy if you could clarify.

**Comment by JonahKr** [comment]
This was explained in a earlier issue here: https://github.com/JonahKr/power-distribution-card/issues/8#issuecomment-704139551 

So ratio is equivalent to your own consumption rate:
`Your Own Power Consumption/ Produced Power` -> so in this case (home consumption / solar production)

Autarky is calculated as:
`Your Own Power Consumption / Total Consumption` -> so in this case (home consumption / homeconsumption + if power is exported to the grid)

This will however change with 1.5 to some more understandable formulas.
I was just using the official formulas until now becaus ei thought it was the right thing but I don't think that was the right decision.
