### ISSUE TITLE
layout goes wrong with more consumer

### ISSUE THREAD

**Issue by danps1** [JonahKr/power-distribution-card#23]
I really love this card. Thanks so much for creating it!
I expect that I am trying to use the card for a display beyond what it was designed for, but I have notices that when I add more than 3 consumers, the layout of the card gets a bit mixed up...
<img width="491" alt="image" src="https://user-images.githubusercontent.com/36139437/95754572-f8273180-0cee-11eb-8bcd-04b3d396aca0.png">
As you can see, I basically group my energy sensors by type or function, and I'd love to use the card to show a live breakdown of energy usage in my house.
Thanks again!

**Comment by JonahKr** [comment]
@danps1 You made my day 😂 thanks alot. I will take a look at this most certainly... I actually didn't think anyone would use more then 6 elements... But I was proved wrong apparently..

Additionally: your solar arrow direction seems wrong... This could either mean you are still running v1.4 or you will need to invert the value 😉

**Comment by danps1** [comment]
Awesome - thanks for that!
I know the solar arrow looks wrong but it's actually correct. I took that screenshot at night - when there's no solar production, the solar gateway still draws a very small current, which is what you're seeing there. Here it is in daytime...
<img width="441" alt="image" src="https://user-images.githubusercontent.com/36139437/95789147-b4e9b480-0d28-11eb-8958-d60126464eb1.png">
Running latest version.

**Comment by JonahKr** [comment]
The Grouping of the Items changed in https://github.com/JonahKr/power-distribution-card/commit/9f3742a68e8e951e17e99d6b21857514b56d841f so this is fixed 👍 
This will be included in the next release (today/tomorrow)

Thanks for the Bug Report

**Comment by danps1** [comment]
Looks awesome! Thanks so much 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/36139437/96778314-3c28dd80-1437-11eb-9499-4627138fe714.png">
