### ISSUE TITLE
Produced and Consumed

### ISSUE THREAD

**Issue by willsmarthome** [JonahKr/power-distribution-card#26]
Hi,

First, Great Job, nice Card.
Question:
I have a sensor and this indicates interface to the power supplier.
When de consumed power is lower then the produced power it wil give a negatief value, eq: 400 W or -400 W
Is it posible to use this messurements in the power-distribution-card?

Something like this:
solar: 4000 W
home: 1000 W
grid: -3000 W

Greetings,
Martin

**Comment by JonahKr** [comment]
Hi @willsmarthome 👋 
So just to clarify on how i understood it:
You have a sensor reading values from the grid connection point with negative values when feeding power to the grid.
If thats the case you can just use the standard card configuration and add this sensor with the `grid` preset.

If i got something wrong here, I will need more info then that to give you a concrete answer.

**Comment by willsmarthome** [comment]
Your understandig in correct.

Thanks it's working now.
Sorry for the late response.
