### ISSUE TITLE
More than 4 tiles

### ISSUE THREAD

**Issue by Dario82** [JonahKr/power-distribution-card#27]
Hello,
can you fix this graphic problem when I set more than 4 tiles?
![Cattura](https://user-images.githubusercontent.com/39548149/96685882-0a077500-137e-11eb-9bd1-bf2b1f45824b.JPG)

**Comment by JonahKr** [comment]
Is already fixed in https://github.com/JonahKr/power-distribution-card/commit/9f3742a68e8e951e17e99d6b21857514b56d841f which will be released today. 
Take Care!
