### ISSUE TITLE
Add more than 4 sensors to display

### ISSUE THREAD

**Issue by chheiss** [JonahKr/power-distribution-card#34]
How about adding a few more sonsor values to the display? Like a 5th or 6th small icon with consumption or production values?

**Comment by JonahKr** [comment]
I am but confused tbh. You can add as many as you want already... 1 oder 100 it literally doesn't matter..
Just take a look at the presets in the Readme file

**Comment by JonahKr** [comment]
@chheiss i would need more specific info to understand what you mean

**Comment by JonahKr** [comment]
Closed due to inactivity. Feel free to reopen if you have more information. 👍
