### ISSUE TITLE
Error loading version 1.7

### ISSUE THREAD

**Issue by codedmind** [JonahKr/power-distribution-card#35]
Error loading version 1.7

![image](https://user-images.githubusercontent.com/2910047/99064594-11492980-259e-11eb-8c35-a254d87427bc.png)

**Comment by JonahKr** [comment]
@codedmind ok i will need some more info here:
How did you install it?
Did you restart Hass after installing?
Which browser are you using?

**Comment by codedmind** [comment]
Yeah...restart HA, force reload browser

Chrome on windows

JonahKr <notifications@github.com> escreveu no dia sexta, 13/11/2020 à(s)
11:23:

**Comment by codedmind** [comment]
Can be closed.
Reinstall, force reload, cache, restart, working

**Comment by JonahKr** [comment]
ok good. If it reoccurs please keep me in line. I never had this issue before.
