### ISSUE TITLE
Bar layout improvement

### ISSUE THREAD

**Issue by KNXBroker** [JonahKr/power-distribution-card#37]
Hello, great card! I have tested various cards, but I will definitely go for this card.

I'm not yet sure how to setup the center . In general I like the bars, but I have some comments:
* Two bars are completely confusing me (I never know what is what).  An option to disable one specific bar would be good.
* I don't like the layout when the bars are 0% --> It looks so empty...  Have you already thought of making a border around the bars? Or maybe even better: 

![test](https://user-images.githubusercontent.com/25910703/100004014-2ce6d800-2dc7-11eb-8fce-60f6b23ea698.png)

**Comment by JonahKr** [comment]
Hi there 👋 @KNXBroker ,
So for the first question: take a look at the [Readme](https://github.com/JonahKr/power-distribution-card#what-the-heck-are-these-autarky-and-ratio-calculating).
For the Second one: I will definitely take that on my list of things to do... the background color should be easy and i will include it in 2.0 but the rest will have to wait until i finish the other feature requests.
What you currently can do however is to add the bar card to the center like [this](https://github.com/JonahKr/power-distribution-card#cards-).

Let me know what you think and if you have further ideas...👍

**Comment by KNXBroker** [comment]
Thank you for the background colour!

Regarding the first point, I think have now understood everything. However I still do not know how to keep it in mind... Writing longer Texts is not possible due to the (nice) layout.

Adding Icons? The question is which Icons? A bird for autarcy? Don't know... Or adding mouse over Tips?

Just some ideas... 

Best regards

**Comment by JonahKr** [comment]
So the Single Bar or x-bar is possible since https://github.com/JonahKr/power-distribution-card/commit/6d19b7fc6d0d2479394022204d7aa6e3322f038e 
And the Bars got background here: https://github.com/JonahKr/power-distribution-card/commit/955412372f92b2323a2a3fdc4c0f2a8f98795e30
They will get included in the editor eventually.
