### ISSUE TITLE
Custom Unit of measurement

### ISSUE THREAD

**Issue by Next9999** [JonahKr/power-distribution-card#43]
Suggestion.... Could we show our own Unit of Measure

i am used to work with Amp

Amp produce by the Solar Panel
Amp produce by the car alternator

Amp consume by the Motorhome

tks

**Comment by JonahKr** [comment]
@Next9999  so as far as i understand it you can just change the Unit_of_display and this should solve your thing. Watts is used as an internal unit but how you display it is up to you.
Or do you have some conversion issues?

**Comment by JonahKr** [comment]
Ok i just tried this and it doesn't work ... i'm sorry.  im gonna fix this though

**Comment by JonahKr** [comment]
Fixed in https://github.com/JonahKr/power-distribution-card/commit/b4c3df8a96512a131f70fe0ed2198132bfab592a. I will make a new release once i get finish other issues. Thanks for reporting and Happy new Year 👍
