### ISSUE TITLE
Posibility of 3 bars between data

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#44]
Nice feature with the extra bars.

Actually I would love to be able to have 3 bars between the indicators and icons, in stead of two.

This will demand the bar width and distance between the two bares to be less.

In that case I could have these bars,

To Grid
Own production
total taken from grid

Regards,
@pesor

**Comment by JonahKr** [comment]
Hey there 👋 @pesor ,

The way the Bars are conceptulized atm (with the label anderneath and the value on top) I don't think it would be that easy to implement. Furthermore i am already having troubles getting the card slim enough so i am unsure if this is a good idea to implement at this point in time.
However, if you know your way around with Css, this should be easily achievable with Thomas Loven's [Card Mod](https://github.com/thomasloven/lovelace-card-mod).
For more context: The `center-panel` is  just a *flex-box* container. I see two possibilities here. You could shrink the width of the bars, or enlargen center-panel by manipulating the `card-content` element with `grid-template-columns: 1fr 1fr 1fr;` or whatever ratio you prefer.

I hope i could help you at least a bit and i am sorry that i have to let you kinda down on this one.

Take Care and Happy new Year,

Jonah
