### ISSUE TITLE
No animation and arrows, when not included in calculations.

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#46]
![Energy_overview](https://user-images.githubusercontent.com/3110308/103529896-c43f5080-4e86-11eb-9a04-ac694885ff2c.JPG)

@JonahKr I managed to get your fantastic card to work exactly as I wanted it to.

Impressing card indeed, it now matches how my energy is created and used and stored on the grid.

I explain the Icons, for better understanding of my request.

Solar is what is currently produced by my solar cells

Grid is what is currently sendt to grid, (green) or collected from grid (red)

From/Solar is what is directly outside grid, currently used of the produced energy  from my solar cells

(Fase 3) as my Solar cells are only 2 fases, the 3rd fase always draw power from the grid, no matter what is produced from solar cells.

Home is the total energy consumption currently taking place.

Now to the isssue:

Grid/Bank, is what I have stored on the grid, green in my favor, red in the energy company's favor.

As you can see the measurement is kWh, and this field is not included in any calculations, as it is a pure figure, that constantly updates, according to production/energy usage, to from the grid.

This is a special Danish solution, where if your sun cells were ordered before november 2012, you could use the grid for storage of the production you currently not use, and draw from this when the sun is down. (This solution does not exist anymore), but in my case is valid for another 12 years.)

Now to the request:

I would really like a feature to turn the arrows off, when not including the Icon data in the calculations. Meaning that it only will contain the figures, and not the triangles.

So it looks like this:

![Energy_overview-1](https://user-images.githubusercontent.com/3110308/103530960-b12d8000-4e88-11eb-9eed-b2aac64de025.JPG)

**Comment by JonahKr** [comment]
Hey there @pesor 👋 ,
Glad you still enjoy my card 😉 
I think i know what you mean and actually like it alot. This should be easily implementable so maybe i get it done later today.
Thanks for the Idea and take care!
Jonah

**Comment by JonahKr** [comment]
Okay this should do the job. However it isn't centered as nicely as in your example. This will change automatically once i refactor the CSS part.
