### ISSUE TITLE
Translation option for autarky and ratio

### ISSUE THREAD

**Issue by Schrolli91** [JonahKr/power-distribution-card#52]
I saw that in my German installation, autarky and ratio are always English.
I didn't find this in language JSON files. Maybe this can be added?

AND, big thanks für this nice project :-)

**Comment by JonahKr** [comment]
Hey there 👋🏻 ,
Could you further specify what you mean?
Do you mean the preset settings for bars?
Maybe

**Comment by Schrolli91** [comment]
Yes exactly at the bars ...

**Comment by JonahKr** [comment]
I could make a translation for the default when you create a new bar easily.
For the setting itsself, i would need to change the way the lists of options are generated first. Maybe i can get around to it. 
-> the first one ✔️ and for the second one i may have to postbone it after my exams.
Thanks for bringing this up 👍🏻

**Comment by Schrolli91** [comment]
Just for clarification - i mean this strings in the card
![image](https://user-images.githubusercontent.com/6043382/105509866-4379b480-5cce-11eb-9539-06829bed35e0.png)

**Comment by JonahKr** [comment]
Ok i added this. I tested it once so lets hope it works in the wild.

**Comment by JonahKr** [comment]
I will include this in the next release
