### ISSUE TITLE
Threshold for Animation

### ISSUE THREAD

**Issue by Schrolli91** [JonahKr/power-distribution-card#53]
Is it possible to add some way of set a Threshold for the Animation?
In my case sometimes the Solar-System will report a power of 0.1 Watts.
Thats "nothing" but will show the animation.
![image](https://user-images.githubusercontent.com/6043382/105532398-0ec82600-5ceb-11eb-8dd0-83fcad18bc2c.png)

**Comment by JonahKr** [comment]
Hey there 👋🏻 @Schrolli91 
Good catch. You're on a streak it seems 😉 
I think i will just show no animation if the displayed value is zero. (atm the calculated value is used) I want to keep extra settings to a minimum.
Take Care!

**Comment by Schrolli91** [comment]
> I think i will just show no animation if the displayed value is zero.

I think thats a very good idea. And in my opinion thats enough.
No reason to bloat the settings with hundreds of options 😄
