### ISSUE TITLE
autarky and ratio

### ISSUE THREAD

**Issue by bmoons1975** [JonahKr/power-distribution-card#54]
Is there a possibility to get the autarky and ratio values into graphs?

**Comment by JonahKr** [comment]
Could you further specify what you mean please?

**Comment by bmoons1975** [comment]
Hi,
Both bars can’t be clicked to see a history.
I want to see per day what is the percentage of directly used solar power.
If I have the history of the ratio and autarky then I can add it to grafana.

Hope this is understandable

greetings
Bart

**Comment by z8i** [comment]
I think you will need to define a template sensor in home assistant yourself for these values, then you can access them.

**Comment by bmoons1975** [comment]
Should be strange because this would mean that I don’t need this app anymore and I calculate it myself.

**Comment by JonahKr** [comment]
@z8i is completely right. I can only show the History of a sensor if i can execute the `more-info` [event](https://github.com/JonahKr/power-distribution-card/blob/33176618a7caedcd11ead604119cd07ad2930171/src/power-distribution-card.ts#L214-L224) wich needs a sensor inside homeassistant. 

This lovelace card isn't primarily for calculating values and more a visual addition to homeassistant.
The Calculation is just a small feature.

Setting up template sensors shouldn't be to hard though.

Take Care!
