### ISSUE TITLE
Enrich battery levels

### ISSUE THREAD

**Issue by FrankGBusch** [JonahKr/power-distribution-card#58]
Hi,

found your custom card for lovelace and it's working for a while now. Awesome!! I really like it.

Now I have an idea: wouldn't it be possible to enrich those three marked section with the related battery levels? I already have those sensors available within my home assitant instance and it's just a question of "how" to get them into your custom card.

![image](https://user-images.githubusercontent.com/20207681/110109364-9e162e00-7dad-11eb-976f-df158b7a8956.png)

Thanks in advance
Frank

**Comment by JonahKr** [comment]
Hey there @FrankGBusch 👋

Actually with the newest Version `2.2` which I released yesterday in the evening, a new option called `secondary_info` got added.
This looks like this: (the small 1% at the right side of the icon)
![image](https://user-images.githubusercontent.com/38377070/110110266-d9fdc300-7dae-11eb-83f3-9a15bfc7ed5e.png)
 
You should find the options for that in the visual editor here:
![Screenshot 2021-03-05 123354](https://user-images.githubusercontent.com/38377070/110110447-20ebb880-7daf-11eb-998d-55da1f5d31d3.png)

Or if you are the more *yaml* type of guy, take a look [here](https://github.com/JonahKr/power-distribution-card#entity-configuration).
Let me know if this is what you were looking for. Some more ideas regarding this got collected here: https://github.com/JonahKr/power-distribution-card/issues/13

Take Care and Stay safe! 👍 

Jonah

**Comment by FrankGBusch** [comment]
That was solved quick. Awesome, thank you ;-)

Now it looks like this:

![image](https://user-images.githubusercontent.com/20207681/110120023-ca857680-7dbc-11eb-80ee-fd6595df96aa.png)

Quite cool ... some minor overlap if battery level is at 100%, but I can live with that ;-)

Thanks a lot
Frank

**Comment by JonahKr** [comment]
ok i will try to fix the overlap... that does not look as nice as it should 😅 
Will release a hotfix once i get to it
