### ISSUE TITLE
what means ratio?

### ISSUE THREAD

**Issue by Stephan1908** [JonahKr/power-distribution-card#61]
Hello,

interesting integration!
What exactly does ratio mean? 

Thank you
Greetings 
Steff

**Comment by JonahKr** [comment]
Hey there 👋 @Stephan1908 

Just take a look at the Readme and scroll all the way to the bottom. 

 Take care and stay safe 👍
Jonah

**Comment by Stephan1908** [comment]
Hello Jonah,
Thank you :-).
In german: Wer lesen kann ist klar im Vorteil! 

Stay healthy 
Stephan
