### ISSUE TITLE
Handle Unavailable Sensors

### ISSUE THREAD

**Issue by Gunsmithy** [JonahKr/power-distribution-card#63]
Hi there!

I've just begun using this card and it works great, but I noticed it does not handle sensors that are Unavailable properly.
This occurs when say one of my smart plugs with energy monitoring is unplugged.
Instead of showing "Unavailable" or something to that effect, it shows "NaN W" and an animated arrow despite essentially being 0 consumption.  
Attached is an image of this behaviour.
It seems like changing [this line of code](https://github.com/JonahKr/power-distribution-card/blob/d455c125bc7fc3939cfd2180d6e99387035d0c2c/src/power-distribution-card.ts#L309) to check for NaN should fix the arrow animation, but I leave that up to you! Especially in terms of how to handle the wattage display.  
Thank you for this card!

Dylan

![chrome_2021-03-28_14-26-03](https://user-images.githubusercontent.com/1775711/112763351-231ded00-8fd2-11eb-8170-a3ff49797e02.png)

**Comment by JonahKr** [comment]
Hey there @Gunsmithy, 👋 

Thanks for the bug report. It never occured to me that this wasn't actually handled properly.
Will try to fix it in the next Release.

Take care and Stay safe 👍 
Jonah

**Comment by JonahKr** [comment]
Out of curiosity: Do you think this would be fine?
![image](https://user-images.githubusercontent.com/38377070/112771217-22657500-902b-11eb-92e5-87374104d62d.png)

**Comment by Gunsmithy** [comment]
That's the same behaviour as 0, right? Yeah I think that's fine!  
I don't think that Unavailable needs to be any different personally.  
If I want to know if something lost connection, I would use an Automation anyways, not a Lovelace card.

**Comment by JonahKr** [comment]
Ok thanks. 0 is still displayed as 0 watts or whatever unit btw. I pushed this to the Dev branch and will include it in the next release.
Thanks again for the report. 👍

**Comment by Gunsmithy** [comment]
Thanks for the quick fix! Looking forward to release. :)
