### ISSUE TITLE
hide arrow if value is below x

### ISSUE THREAD

**Issue by mxwi** [JonahKr/power-distribution-card#64]
Hi,

it would be great if you could hide an arrow if the value (pos. or negative) is below a user-defined threshold.

Sometimes my meter returns 100W of import/export because latency deviations. I want to ignore them in on this card. 

![image](https://user-images.githubusercontent.com/32883521/114011444-85de7680-9865-11eb-975f-a80fe31a964a.png)

Well, I guess the picture is unnecessary, but anyway..

**Comment by wowulavega** [comment]
mxwi ....
 darf ich mich hier mit einer Frage einklinken ?
Welche Sensoren benutzt Du in Deinem System ?
Stellen sie positive und negative Richtungen in die Berechnung und wo werden die Werte eingespeist ?
Danke für eine Antwort.
Wolfgang

**Comment by mxwi** [comment]
Hi wowulavega,

PV: Abfrage via Modbus Schnittstelle des Solardedge Wechselrichters. [nur positiv]
Batterie: Abfrage via Modbus Schnittstelle der Varta Batterie. [negativ entladen, positiv laden]
Netz: [PowerGrid Sensor](https://www.memodo.de/heimspeicher/varta/3036/varta-split-core-stromsensor-fuer-pulse/element-s4) der Varta Batterie. Der hängt direkt hinter dem Stromzähler. Abfrage via Modbus Schnittstelle der Varta Batterie. [negativ Bezug, positiv Einspeisung]
Verbrauch: Wird aus den oben genannten Werten errechnet. [nur negativ]
`value_template: '{{(states("sensor.PV_ACPowerValue") | float - (states("sensor.varta_power_grid_kw") | float + (states("sensor.Varta_Aktuelle_Leistung") | float /1000))) | round(2)}}'`

Ich hoffe das beantwortet deine Frage, wenn nicht melde dich einfach nochmal.

**Comment by JonahKr** [comment]
Hey there @mxwi 👋,
Quick question regarding this.
If the the value is below you threshold, should no value be displayed or just no arrows 🤔

**Comment by mxwi** [comment]
> Hey there @mxwi 👋,
> Quick question regarding this.
> If the the value is below you threshold, should no value be displayed or just no arrows 🤔

I think the best implemenation for the most usecases would be the to define a new variable "min. deviations" (default: 0).
That value must be exceeded before the UI reacts to it (arrows and values). It has to work with signed values, too.

So I would have a solution for my usecase (no arrows and the value would be zero), but it would not be limited to it.
To answer your question. The arrow should be hidden.

**Comment by spali** [comment]
> > Hey there @mxwi 👋,
> > Quick question regarding this.
> > If the the value is below you threshold, should no value be displayed or just no arrows 🤔
> 
> I think the best implemenation for the most usecases would be the to define a new variable "min. deviations" (default: 0).
> That value must be exceeded before the UI reacts to it (arrows and values). It has to work with signed values, too.
> 
> So I would have a solution for my usecase (no arrows and the value would be zero), but it would not be limited to it.
> To answer your question. The arrow should be hidden.

don't miss the icon colors ;)
My battery is always leaking (actually counted as discharge) < 20W and this would allow me to "ignore" everything below 20W and help to not highlight the battery with (in my case) a red icon due battery discharge. In my case, I care more the icon color than the arrows, but I think can be the same setting.

**Comment by JonahKr** [comment]
In [v2,.3](https://github.com/JonahKr/power-distribution-card/releases/tag/v2.3) a `threshold` option got added for items.
I hope this works for you as intended.

Thank you very much for your suggestion and take care! 👍

**Comment by mxwi** [comment]
Thank you!
