### ISSUE TITLE
entities used for bars not clickable

### ISSUE THREAD

**Issue by da-anda** [JonahKr/power-distribution-card#67]
Hi,

thank you very much for this super cool card. Would it be possible to make the bars clickable (secondary info) when an entity is used for those? That's basically the only thing missing to make it perfect for me.

Thanks.

**Comment by JonahKr** [comment]
In [v2,.3](https://github.com/JonahKr/power-distribution-card/releases/tag/v2.3) this got added!
Thank you very much for your suggestiona nd take care ! 👍
