### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#7]
I have implemented it like this in Manual Card:

type: 'custom:power-distribution-card'
title: Overview
battery: none
home: sensor.energy_consumption
solar: sensor.fronius_pac
grid: sensor.kamstrup_activepowerplus
autarky: sensor.autarky  ???
ratio: sensor.ratio      ??? 

I do not have a battery, but the other sensors are correct and showing data in my other cards.

Do this card need specific sensors, or what am I doing wrong

**Comment by pesor** [comment]
Hi Johan,

Thanks for quick answer.

I will be pleased to help you Beta test,
I am running Home Assistant on a Synology DS918+, with all extra ram, and read/write cashes, and it is running in Docker.

I did input as you wrote, but that did not help.

I have included some screen prints to show:
This is the input:

[cid:image001.png@01D69BC8.873D8A10]

I used HACS to install, here is the installed card:
[cid:image002.png@01D69BC8.873D8A10]


And this is the file installation:

[cid:image003.png@01D69BC8.D1663830]

Do I miss anything:

Best regards,
Per Rose





Fra: JonahKr <notifications@github.com>
Sendt: 5. oktober 2020 17:47
Til: JonahKr/power-distribution-card <power-distribution-card@noreply.github.com>
Cc: Per Rose <post@per-rose.dk>; Mention <mention@noreply.github.com>
Emne: Re: [JonahKr/power-distribution-card] How does it work? (#7)


Hi @pesor<https://github.com/pesor> 👋 ,

type: 'custom:power-distribution-card'



title: Overview



home: sensor.energy_consumption



solar: sensor.fronius_pac



grid: sensor.kamstrup_activepowerplus

This should be completely fine for you then.
Autarky aswell as ratio is calculated automatically if no sensor is provided for it.

There will be some significant changes in the next version which i am currently preparing. Which will make this easier to understand... I will include a new version for it in this thread if you want to.

I Hope i could help 👍

**Comment by JonahKr** [comment]
@pesor Sadly the images didn't get transfered as it seems. You can drag and drop them in the online issue commenting tool and they will be uploaded to github under your user account.
A upload of just the Card itsself  and its configuration would already help me alot.

**Comment by pesor** [comment]
@JonahKr Where have you stored the images, I do not find them in the repository?

**Comment by JonahKr** [comment]
i meant the images in the Email 

> Hi Johan, Thanks for quick answer. I will be pleased to help you Beta test, I am running Home Assistant on a Synology DS918+, with all extra ram, and read/write cashes, and it is running in Docker. I did input as you wrote, but that did not help. I have included some screen prints to show: This is the input: [cid:image001.png@01D69BC8.873D8A10] I used HACS to install, here is the installed card: [cid:image002.png@01D69BC8.873D8A10] And this is the file installation: [cid:image003.png@01D69BC8.D1663830] Do I miss anything: Best regards, Per Rose 

They are not being displayed for me.... 

The only image in this repository is being referenced from the README.md and is located here : https://github.com/JonahKr/power-distribution-card/tree/master/examples

**Comment by pesor** [comment]
There were no images in the E-mail!

Fra: JonahKr <notifications@github.com>
Sendt: 6. oktober 2020 10:36
Til: JonahKr/power-distribution-card <power-distribution-card@noreply.github.com>
Cc: Per Rose <post@per-rose.dk>; Mention <mention@noreply.github.com>
Emne: Re: [JonahKr/power-distribution-card] How does it work? (#7)


i meant the images in the Email

Hi Johan, Thanks for quick answer. I will be pleased to help you Beta test, I am running Home Assistant on a Synology DS918+, with all extra ram, and read/write cashes, and it is running in Docker. I did input as you wrote, but that did not help. I have included some screen prints to show: This is the input: [cid:image001.png@01D69BC8.873D8A10] I used HACS to install, here is the installed card: [cid:image002.png@01D69BC8.873D8A10] And this is the file installation: [cid:image003.png@01D69BC8.D1663830] Do I miss anything: Best regards, Per Rose

They are not being displayed for me....

The only image in this repository is being referenced from the README.md and is located here : https://github.com/JonahKr/power-distribution-card/tree/master/examples

**Comment by JonahKr** [comment]
I mean the screenshots....
![Screenshot (17)_LI](https://user-images.githubusercontent.com/38377070/95179012-608e8400-07c0-11eb-92aa-97a39452855a.jpg)

**Comment by pesor** [comment]
@JonahKr I misunderstood you, I thought it was an image for the card.

Here are the correct images of my setup

![jonah-2](https://user-images.githubusercontent.com/3110308/95179431-e7436100-07c0-11eb-9610-a2b0cbd1534a.png)
![jonah-1](https://user-images.githubusercontent.com/3110308/95179437-e7dbf780-07c0-11eb-9752-eaa8c1f52b6b.png)
![jonah-3](https://user-images.githubusercontent.com/3110308/95179438-e8748e00-07c0-11eb-9e81-a9d641788b80.png)

**Comment by pesor** [comment]
@JonahKr Sorry, It works now, I had to restart Home Assistant, so everything OK.

Sorry for the inconveinency I caused you, but thanks for quick answers..

**Comment by JonahKr** [comment]
Perfect no problem 👍
