### ISSUE TITLE
Adaptive Unit Display with different Values (kW -> kWh)

### ISSUE THREAD

**Issue by Aruta79** [JonahKr/power-distribution-card#71]
Can you add options to display Wh and kWh? I guess this would take a few lines in the render code to select between the following options:
- W, kW and adaptive for power
- Wh, kWh and adaptive_h for energy

The user could then choose what gets displayed, and the comment about kW and kWh in your readme text could be taken away.

Thanks in advance.

**Comment by JonahKr** [comment]
Hey there @Aruta79 👋 ,

There already have been some discussions about how the difference between power and energy should be handled and the result so far was to treat them the same in logic. (I know its wrong from a scientific standpoint)

I have the problem however, that if i would add this, it would open the door for people wanting it with `VAh` or something else.
Thats why i'm not sure if the right approach would be to just add another input option.
I will think about different ways and take care of this although probably not in the next 2 weeks.

Take care and stay safe!

Jonah

**Comment by JonahKr** [comment]
In [v2,.3](https://github.com/JonahKr/power-distribution-card/releases/tag/v2.3) I made the adaptive option sensitive to whatever the unit_of_measurement is set to.
E.g.
Unit_of_measurement: kWh -> Wh and kWh
Unit_of_measurement: kAV -> AV and kAV

I hope this takes care of your proposal.

Thank you very much and Take care ! 👍
