### ISSUE TITLE
Unable to install card via HACS or Manually

### ISSUE THREAD

**Issue by CrouchingWorm** [JonahKr/power-distribution-card#73]
Hey there, just came across this card. Love it!
However I don't seem to be able to install it either via HACS or manually..
I've got a bunch of custom and HACS cards already loaded into my HA environment But can't seem to get thi card going.
I'm just about to install my battery next week in my PVA environment. It'd be awesome to get this up and running.

When I install via HACS, all I get is a spinning wheel icon which never completes. When I go into the Community section of HACS, It indicates the install didn't complete.
I've tried both Version 2.3 and 2.2. Same outcome.
When I install manually (per the guide), I'm unable to use the custom repository (not found).

My environment:
HA 2021.6.6 9 (supervised)
OS Linux (4.19.0-17-amd64)
HACS Version 1.13.2
HACS Installed Repositories 26

Any clues?
Nothing meaningful in the logs that I can tell..
I know I haven't given you much to work with..

**Comment by JonahKr** [comment]
Hey there @CrouchingWorm 👋 
I reran the release action and rebuilt the js file. 
Try uninstalling and reinstalling the file.
Don't forget to Reload the lovelace resources afterwards.

Let me know if it worked for you!

**Comment by CrouchingWorm** [comment]
Thanks so much for the speedy reply.. Unfortunately the same result.
![image](https://user-images.githubusercontent.com/35030235/124242660-54253500-db60-11eb-98f0-dd8344f3a526.png)
It doesn't progress past this point (in HACS)..
Weird.

**Comment by JonahKr** [comment]
Could you execute this command to get the file hash?
This way we can find out if it got installed properly: ` md5sum \config\www\community\power-distribution-card\power-distribution-card.js`
It should equal to `2e4f5738442a393c66a84418f3848b7e` 
If this is the case than everything got installed properly and you would just need to reload the lovelace resources.

**Comment by CrouchingWorm** [comment]
I got something different:
bash-5.0# md5sum www/community/power-distribution-card/power-distribution-card.js
afa871b5988fb36176bd8068d531a108  www/community/power-distribution-card/power-distribution-card.js

I'm sorry to sound silly.. What am I supposed to do in the discord server? do I navigate my way through logging/chatting about the issue?

**Comment by JonahKr** [comment]
It seems like your issue is that HACS isn't installing the card properly hence the different Checksum.
So there are 2 Options:
1. You could post the question in the Hacs discord and maybe some of the Hacs team (Ludeus for example) knows whats wrong or
2. You just install the card manually by copying the js file from the release tab into the folder. `wget https://github.com/JonahKr/power-distribution-card/releases/download/v2.3/power-distribution-card.js`

**Comment by CrouchingWorm** [comment]
Thanks for the explicit explanation. Makes sense.
I'm okay with it being installed manually.
HOWEVER, this is what I get when I wget from the CLI of my HA docker...
````
bash-5.0# wget https://github.com/JonahKr/power-distribution-card/releases/download/v2.3/power-distribution-card.js
Connecting to github.com (52.64.108.95:443)
Connecting to github-releases.githubusercontent.com (185.199.110.154:443)
saving to 'power-distribution-card.js'
power-distribution-c 100% |****************************************|  103k  0:00:00 ETA
'power-distribution-card.js' saved
bash-5.0# md5sum power-distribution-card.js
afa871b5988fb36176bd8068d531a108  power-distribution-card.js
````

These are the permissions of the folder..
bash-5.0# ls -la
total 320
drwxr-xr-x    2 root     root          4096 Jul  2 20:13 .
drwxr-xr-x   15 root     root          4096 Jul  2 18:11 ..
-rwxr--r--    1 root     root        106131 Jul  2 09:56 power-distribution-card OLD.js
-rw-r--r--    1 root     root        106131 Jul  2 20:13 power-distribution-card.js
-rwxr--r--    1 root     root        106131 Jul  2 18:13 power-distribution-card.js.old

What the heck!?
Surely I can't be that hopeless, I'm getting this wrong.
I orginally downloaded the .js via my windows machine and tranfered it via a SAMBA share..

**Comment by JonahKr** [comment]
I rechecked the checksum and `afa871b5988fb36176bd8068d531a108` is correct. sorry my bad. I took the one before i reran the release action.😞 

This means the installation before was actually complete.
Can you delete the new downloaded file and rename the old one back to `power-distribution-card.js` and just restart HA?
That should do the trick.
If not, I will dig further into it

**Comment by CrouchingWorm** [comment]
HA! That's funny. Something I'd do. Phew :)
The .js files are there because I manually created the file structure and coppied it/them there.
The HACS install never completes. I'm okay with a manual approach at this stage.

I'll restart HA in the morning if that's okay? I have some integrattion which misbehave if they can't see certain devices when it boots.
They'll all be back online in the morning. Sorry to be a nuisance.
Super thankful you're taking the time to look into this for me.

**Comment by CrouchingWorm** [comment]
Okay, so rebooted HA.
Short version: The card is now available. Thank you so much.

Longer explanation, Chrome has caused me to waste our time. The card isn't available in Chrome browsers. It's weird.
The card is available in the iOS App, Edge and Safari. Not chrome. Chrome's confused me before, so I'm comfortable saying it's a local issue.

THANK YOU!

**Comment by CrouchingWorm** [comment]
Okay, so rebooted HA.
Short version: The card is now available. Thank you so much.

Longer explanation, Chrome has caused me to waste our time. The card isn't available in Chrome browsers. It's weird.
The card is available in the iOS App, Edge and Safari. Not chrome. Chrome's confused me before, so I'm comfortable saying it's a local issue.

THANK YOU!

**Comment by JonahKr** [comment]
Glad you got it working🎊

With Chrome it actually makes sense. It tries to cache any and everything to speed up websites. This has the downside of not working well with changes in ressources. For development I had to disable caching to use it or any chromium based browser.
