### ISSUE TITLE
wrong values

### ISSUE THREAD

**Issue by legi1** [JonahKr/power-distribution-card#74]
Since the last update? I have a problem with the kW values. E. g. the value Garage shows 652 kW instead of 0.652 kw.
See picture
<img width="491" alt="Bildschirmfoto 2021-07-04 um 08 21 28" src="https://user-images.githubusercontent.com/11909017/124375406-54c5e480-dca2-11eb-9c30-357460202c55.png">

**Comment by JonahKr** [comment]
Ok thanks for the hint. Will take a look and push a hotfix if i'm able to replicate!

**Comment by legi1** [comment]
do you need my YAML?

**Comment by JonahKr** [comment]
Would help alot thanks

**Comment by legi1** [comment]
Here it is:
`type: custom:power-distribution-card
title: Photovoltaik Anlage
animation: slide
entities:
  - solar:
      entity: sensor.e3dc_solar_hausdach
      icon: mdi:weather-sunny
      name: Hausdach
      unit_of_display: adaptive
    entity: sensor.e3dc_solar_hausdach
    name: Hausdach
    decimals: '3'
    unit_of_display: kW
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    preset: solar
    icon: mdi:home-roof
    invert_value: false
  - decimals: '3'
    display_abs: true
    name: Garage
    unit_of_display: kW
    icon: mdi:garage
    producer: true
    entity: sensor.e3dc_solar_extern_garage
    preset: producer
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    invert_value: true
  - grid:
      entity: sensor.e3dc_netzbezug
      name: Netz
      unit_of_display: adaptive
      invert_value: false
    entity: sensor.e3dc_netzbezug
    name: Netzbezug
    decimals: '3'
    unit_of_display: kW
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    preset: grid
    icon: mdi:transmission-tower
  - battery:
      entity: sensor.e3dc_batterie
      icon: mdi:battery-50
      name: Batterie
      unit_of_display: adaptive
      invert_value: true
    entity: sensor.e3dc_hausbezug
    name: Hausbezug
    decimals: '3'
    unit_of_display: kW
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    preset: consumer
    icon: mdi:home-assistant
    invert_value: true
  - home:
      entity: sensor.e3dc_hausbezug
      name: Haus
      unit_of_display: adaptive
      invert_value: true
    entity: sensor.e3dc_batterie
    name: Batterie
    decimals: '3'
    unit_of_display: kW
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    preset: battery
    icon: ''
    invert_value: true
  - decimals: '3'
    display_abs: true
    name: Auto
    unit_of_display: kW
    consumer: true
    icon: mdi:car-electric
    entity: sensor.e3dc_wallbox
    preset: car_charger
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    invert_value: true
center:`

**Comment by JonahKr** [comment]
Hey there @legi1 👋 
Thanks again for the Bug report!
Its fixed with the latest version.

Take Care!

**Comment by legi1** [comment]
thanks for the fast repair!
