### ISSUE TITLE
Animation "flash" not working on iOS

### ISSUE THREAD

**Issue by timolol** [JonahKr/power-distribution-card#77]
Animation "flash" does not seem to work on iOS device. Test on Safari browser, Chrome browser and the official companion app.

**Comment by JonahKr** [comment]
Hey there 👋 
Thanks again for reporting.
Could you check if the `slide` animation works for you?
That would help alot.

Thanks in advance!

**Comment by timolol** [comment]
Hi @JonahKr ! Yes `slide` animation works on the iOS device. I am sorry I did not even make the effort to look at your code. A snap learning on some html svg, I think I have identified the issue...
` 
           <g id="flash-${index}">
              <use
                href="#arrow-${direction}"
                x="0"
                style="animation-delay: ${direction == 'right' ? 0 : 2}s;"
                id="a-flash"
              />
              <use href="#arrow-${direction}" x="20" style="animation-delay: 1s;" id="a-flash" />
              <use
                href="#arrow-${direction}"
                x="40"
                style="animation-delay: ${direction == 'right' ? 2 : 0}s;"
                id="a-flash"
              />
`
I think the unclosed '<' tag might be the reason? ;)

**Comment by timolol** [comment]
I have done some further testing. It seems like with webkit (or Safari on iOS at least) is not recognising the css property 'animation' within the 'defs' element. Not sure if is meant to be an expected behaviour? Other css styling like 'fill' or 'fill-opacity' works fine.

Could modifying the function '_render_arrow' to somehow only return the appropriate html / svg elements work?

**Comment by JonahKr** [comment]
Yeah. I was having a chat with the ios homeassistant devs and i will need to rename the webkit animations.
Sadly i cannot really test it though because i have no ios device at home.
I will try to patch it and release a beta release tomorrow.
Maybe you can try it then to see if it fixed your issue?

**Comment by timolol** [comment]
Happy to do that? The beta version be installed via the HACS interface right?

**Comment by JonahKr** [comment]
Ok i pushed a beta, would help alot if you could confirm that this fixed it 🙏

**Comment by JonahKr** [comment]
@timolol any update? Otherwise i would close the issue as stale and would just release the changes the next time other changes get released.

**Comment by timolol** [comment]
@JonahKr Apologies for the late reply. We have a newborn since I wrote to you last and life is a little upside down at the moment. 😊

I have updated and reinstalled your beta add on version 2.3.2-b1. Sorry to say, setting to “Flash” still did not work as expected.

**Comment by JonahKr** [comment]
First of all: Congratulations! I hope your kid and partner are well and healthy and I wish you all the best for the future 🎉 
Regarding the Beta: **Dang it** - I will have to try harder.

**Comment by netmb** [comment]
Any news on this? Btw: Slide-Animation consumes a lot of cpu-cycles in Safari - so this is no alternative on Mac/iOS.

**Comment by JonahKr** [comment]
That's good to know 🤔 I wasn't aware of this. I think the issue is related to the way safari handles svg animation rendering. I would probably need to change the current arrow animation setup. Maybe if i can find some time i can look for a new approach regarding this.

**Comment by guzzit3** [comment]
Hi, really like this card.
 Is it possible to change the units displayed above the bars. I have a water heater which has 2 entities for temperature in °C. They work really well with bars, however they are displayed as % , it would be great if I could change this  to degrees C.
Many thanks Pete

**Comment by JonahKr** [comment]
Hey there @timolol @netmb 👋 
It's been a while and i hope you are all doing well!
I just changed all animations from using vectors to pure CSS, so hopefully that should resolve the performance as well as the rendering issues. I sadly don't have access to a Mac so it would be wonderful if you could give me some feedback on the new Release!

Thanks in advance 😄

**Comment by netmb** [comment]
Hey, thanks a lot. It's working now. Tried it in Home-Assistant-App (Mac & iOS) and Safari. No issues at all !

**Comment by timolol** [comment]
Heya! Can I just say thanks for keeping an eye on this and maintaining it
for us? Unfortunately, my inverter is not communicating with HA because of
some modbus issue after an uninformed firmware update. So I am not able to
test the arrows. But I trust it must be working and will let you know
otherwise when my inverter is back online!

Hope you are all doing well too!
