### ISSUE TITLE
Problems with setting up autarky and ratio

### ISSUE THREAD

**Issue by ashwin2101** [JonahKr/power-distribution-card#79]
Hi first I want to say, great job! I like the power-distrubution-card

How do I get the autarky and ratio to get work?
I have attached my card configuration

![image](https://user-images.githubusercontent.com/56930394/129054129-8b735c47-9f94-40d1-ba80-0aacd5cceb03.png)

**Comment by JonahKr** [comment]
Hey there @ashwin2101 👋 
First of all your values seem a bit odd:  If I assume the power towards the grid is outbound, you would need to check the `invert_value` option for it.
Secondly there is a gap of ~0.8kW. This will mess with your calculations.
You can find a breakdown of the logic here:
https://github.com/JonahKr/power-distribution-card#what-the-heck-are-these-autarky-and-ratio-calculating

Let me know if that helped and Take care ! 👍 

Jonah

**Comment by JonahKr** [comment]
Since there hasn't been any response so far i will close this issue and mark it as stale. If you want to continue this thread you can reopen the issue anytime.
Take Care! 👍
