### ISSUE TITLE
autarky percent calculation issue

### ISSUE THREAD

**Issue by vk2him** [JonahKr/power-distribution-card#8]
When autarky is being automatically calculated, sometimes it displays a figure that isn't a whole number and it displays many zeros with a value, ie, 51.00000000007%

The percent should be fixed to a whole number to avoid this issue - thanks

**Comment by vk2him** [comment]
Here is an example of the issue 

![image](https://user-images.githubusercontent.com/22878629/95154108-cd177c00-07dc-11eb-8e42-82c61de7234d.png)

**Comment by JonahKr** [comment]
@vk2him may i ask which version you are running? This issue should actually be resolved with https://github.com/JonahKr/power-distribution-card/commit/ad0e9acf139bb18c072859b122ee71ac903184d0 and therefore already dealt with in v1.4 . Maybe check if you have the older Alpha installed instead.

**Comment by vk2him** [comment]
Running v1.4.0 ... installed via HACS - thanks

**Comment by JonahKr** [comment]
ok i will take a further look at it. thanks 👍

**Comment by vk2him** [comment]
Interesting - the power-distribution-card.js code inserted by HACS looks nothing like the code from your repo - here is a snip of v1.4.0 installed via HACS:

`/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
function t(t,e,i,r){var n,s=arguments.length,o=s<3?e:null===r?r=Object.getOwnPropertyDescriptor(e,i):r;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)o=Reflect.decorate(t,e,i,r);else for(var a=t.length-1;a>=0;a--)(n=t[a])&&(o=(s<3?n(o):s>3?n(e,i,o):n(e,i))||o);return s>3&&o&&Object.defineProperty(e,i,o),o
/**
 * @license
 * Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at
 * http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at
 * http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at
 * http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at
 * http://polymer.github.io/PATENTS.txt
 */}const e="undefined"!=typeof window&&null!=window.customElements&&void 0!==window.customElements.polyfillWrapFlushCallback,i=(t,e,i=null)=>{for(;e!==i;){const i=e.nextSibling;t.removeChild(e),e=i}},r=`{{lit-${String(Math.random()).slice(2)}}}`,n=`\x3c!--${r}--\x3e`,s=new RegExp(`${r}|${n}`);class o{constructor(t,e){this.parts=[],this.element=e;const i=[],n=[],o=document.createTreeWalker(e.content,133,null,!1);let l=0,h=-1,u=0;const{strings:p,values:{length:m}}=t;for(;u<m;){const t=o.nextNode();if(null!==t){if(h++,1===t.nodeType){if(t.hasAttributes()){const e=t.attributes,{length:i}=e;let r=0;for(let t=0;t<i;t++)a(e[t].name,"$lit$")&&r++;for(;r-- >0;){const e=p[u],i=d.exec(e)[2],r=i.toLowerCase()+"$lit$",n=t.getAttribute(r);t.removeAttribute(r);const o=n.split(s);this.parts.push({type:"attribute",index:h,name:i,strings:o}),u+=o.length-1}}"TEMPLATE"===t.tagName&&(n.push(t),o.currentNode=t.content)}else if(3===t.nodeType){const e=t.data;if(e.indexOf(r)>=0){const r=t.parentNode,n=e.split(s),o=n.length-1;for(let e=0;e<o;e++){let i,s=n[e];if(""===s)i=c();else{const t=d.exec(s);null!==t&&a(t[2],"$lit$")&&(s=s.slice(0,t.index)+t[1]+t[2].slice(0,-"$lit$".length)+t[3]),i=document.createTextNode(s)}r.insertBefore(i,t),this.parts.push({type:"node",index:++h})}""===n[o]?(r.insertBefore(c(),t),i.push(t)):t.data=n[o],u+=o}}else if(8===t.nodeType)if(t.data===r){const e=t.parentNode;null!==t.previousSibling&&h!==l||(h++,e.insertBefore(c(),t)),l=h,this.parts.push({type:"node",index:h}),null===t.nextSibling?t.data="":(i.push(t),h--),u++}else{let e=-1;for(;-1!==(e=t.data.indexOf(r,e+1));)this.parts.push({type:"node",index:-1}),u++}}else o.currentNode=n.pop()}for(const t of i)t.parentNode.removeChild(t)}}const a=(t,e)=>{const i=t.length-e.length;return i>=0&&t.slice(i)===e},l=t=>-1!==t.index,c=()=>document.createComment(""),d=/([ \x09\x0a\x0c\x0d])([^\0-\x1F\x7F-\x9F "'>=/]+)([ \x09\x0a\x0c\x0d]*=[ \x09\x0a\x0c\x0d]*(?:[^ \x09\x0a\x0c\x0d"'`<>=]*|"[^"]*|'[^']*))$/;function h(t,e){const{element:{content:i},parts:r}=t,n=document.createTreeWalker(i,133,null,!1);let s=p(r),o=r[s],a=-1,l=0;const c=[];let d=null;for(;n.nextNode();){a++;const t=n.currentNode;for(t.previousSibling===d&&(d=null),e.has(t)&&(c.push(t),null===d&&(d=t)),null!==d&&l++;void 0!==o&&o.index===a;)o.index=null!==d?-1:o.index-l,s=p(r,s),o=r[s]}c.forEach(t=>t.parentNode.removeChild(t))}const u=t=>{let e=11===t.nodeType?0:1;const i=document.createTreeWalker(t,133,null,!1);for(;i.nextNode();)e++;return e},p=(t,e=-1)=>{for(let i=e+1;i<t.length;i++){const e=t[i];if(l(e))return i}return-1};
/**
 * @license
 * Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at
 * http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at
 * http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at
 * http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at
 * http://polymer.github.io/PATENTS.txt
 */
const m=new WeakMap,g=t=>"function"==typeof t&&m.has(t),f={},_={};
/**
 * @license
 * Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at
 * http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at
 * http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at
 * http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at
 * http://polymer.github.io/PATENTS.txt
 */

snip`

**Comment by JonahKr** [comment]
@vk2him i was able to replicate the error and will fix it with the next update... thank you very much 👍 

And for the code: Yes this is correct. The repository is written in a language called [typescript](https://www.typescriptlang.org/) which improves error rates by adding types to javascript. Typescript then needs to be compiled to javascript to be usable.
Thats why you cannot really understand what this js file is doing.

**Comment by JonahKr** [comment]
So ratio is equivalent to your own consumption rate: 
`Your Own Power Consumption/ Produced Power` -> so in this case (home consumption / solar production)

Autarky is calculated as:
`Your Own Power Consumption / Total Consumption` -> so in this case (home consumption / homeconsumption + if power is exported to the grid)

There obviously is an error there so i will check it out.

**Comment by vk2him** [comment]
Thanks Jonah - maybe I don't understand your interpretation of Autarky - to me it means whether you are self-sufficient so the calculation would be the inverse of yours? (solar generated + battery supplied)/home consumption. This might explain why your calculation shows 50% as it should be 0%

cheers

**Comment by JonahKr** [comment]
This got fixed with https://github.com/JonahKr/power-distribution-card/pull/15 and will be included in the next release 👍 
I changed the formulas to more reasonable and understandable ones.
