### ISSUE TITLE
Preset Features

### ISSUE THREAD

**Issue by ccspack** [JonahKr/power-distribution-card#86]
Absolutely love the new preset features added in the last update, but my numbers are 3 digits & have kWh as the unit, get spread to two lines & therefore the sell figure gets pushed outside the box. I’ll have to try templates to shorten the data. 
   But I’d love similar data for total solar production & others like total for car, pool, battery import/export since last fill. But no pressure, keep up the great work.

**Comment by JonahKr** [comment]
Hi there @ccspack 👋,

Glad you like it.
Could you maybe share a screen shot of the issue so I can get rid of it?
Thanks alot in advance 👍

**Comment by ccspack** [comment]
Sure, too easy… 
![3AD58212-DE22-46D9-905A-DE3D7086F884](https://user-images.githubusercontent.com/85019945/137605767-5297d865-ed4a-4223-b80b-60afd2ff6e54.jpeg)

**Comment by JonahKr** [comment]
Ok it took a while but I am finally getting some time to get rid of a few issues. I applied a fix by just decreasing the font size and removing the space in-between the number and the unit. I will release the new version the next few days.

Take care and thanks for reporting ! 👍
