### ISSUE TITLE
Add a setting to change arrow color

### ISSUE THREAD

**Issue by mumpf** [JonahKr/power-distribution-card#88]
I love your card and everything looks fine, but I am missing an option to change the arrow colors.
Would be great, if you could add this feature.

Regards,
Waldemar

**Comment by JonahKr** [comment]
Hey there @mumpf 👋
Do you only want to set the arrow color for a item or want it to be changeable depending on the state?

Thanks in advance and take care! 👍

**Comment by JonahKr** [comment]
Hey there 👋 
I added arrow animations as well as an color threshold per entity.
I hope you will like it!
The new version will probably be released tomorrow or the following days.

Take care and stay safe! 👍 
Jonah
