### ISSUE TITLE
Value dependant color changes

### ISSUE THREAD

**Issue by vk2him** [JonahKr/power-distribution-card#9]
I like the idea of this card - can you consider a change so that the colours of the entities change depending on whether they are producing or consuming power?

For example, the house will always be Red as it is always consuming power, however if power is being exported then it should be green and red if it is importing. This way it is easy to tell at a glance if excess power is available.

Autarky could also have a range of colours - 0-30% = Red  30-50% - Orange - 50-70 % light green - 70-100% dark green

Thanks

**Comment by JonahKr** [comment]
I like the idea of this, altough it becomes harder to implement with the next update.
It would be quite easy to change the color of a item-icon depending on a value but to change icons of different items ( e.g. home if power is exported) will be harder. Maybe i could create some kind of preset for this.
Thank you very much for the idea 👍

**Comment by vk2him** [comment]
The idea comes from a device I currently use to visualise my consumption/production called a Flukso.

See last image at this repo link [https://github.com/gebhardm/flmlocal](url)


![](https://github.com/gebhardm/flmlocal/blob/master/images/flm03_consumption.png)

**Comment by JonahKr** [comment]
Added in #9 and is in 2.0
