### ISSUE TITLE
Lovelace resource file is null - custom element doesn't exist

### ISSUE THREAD

**Issue by LucaDiba** [JonahKr/power-distribution-card#98]
Hi! I installed the power distribution card using HACS, however, at first, the card didn't show up and it said that `Custom element doesn't exist: power-distribution-card.`

After debugging, I found out that, at Configuations > Dashboards > Resources, the resource generated by power-distribution-card had the following URL: `/hacsfiles/lovelace-swipe-navigation/null?hacstag=nnn`, where `nnn` was a number. Since I haven't found anything about it among the issues, I thought it was due to some steps I missed so I just changed the URL to `/hacsfiles/power-distribution-card/power-distribution-card.js?hacstag=nnn`. After doing so, I was getting an error on HACS that said that one Lovelace element was having a problem, but since it was working on the frontend it was fine to me.

Today, after upgrading the card to the newest version, it didn't work anymore. I went to the resources and noticed that the URL had that `null` again: `/hacsfiles/power-distribution-card/null?hacstag=28357825725`. By changing it to `/hacsfiles/power-distribution-card/power-distribution-card.js?hacstag=28357825725` it worked again. After doing so, HACS started showing me again the error message, but the card is working now.

Is there any information you might need to debug this behaviour?

Thanks!

**Comment by JonahKr** [comment]
Hey there 👋 

I Have never encountered install issues with HACS to be fair. Do other custom-cards work for you just fine?

I asked in the HACS publisher thread on discord so maybe someone can chime in if they had something similar happen before.
https://discord.com/channels/606225571898327139/677520492508348416/931602446621491260

Take care and stay Safe! 👍

**Comment by JonahKr** [comment]
Ok i got a response from the master himself:
![image](https://user-images.githubusercontent.com/38377070/149560360-bf26bf90-dad3-4c58-83e2-eb3426c805d7.png)
`Update HACS and redownload it, was an USA-tur with 0.19.0`

Let me know if that solves the issue for you!
Thanks for reporting 😄
